"""Full nonlinear MLP trained in a known k-dimensional parameter subspace.

All P parameters of an MLP are represented as theta = theta0 + U z, where U
has k orthonormal columns and only z is optimised. Targets on a fixed dataset
are generated by the same MLP at a quasiperiodically driven z_star(t). Exact
backpropagation is computed through both MLP layers and projected with U.T.
"""

from __future__ import annotations

import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import spearmanr

import estimators as E
import systems as S

HERE = Path(__file__).resolve().parent
OUT = HERE / "results" / "exp14_mlp_intrinsic_subspace_k20"
OUT.mkdir(parents=True, exist_ok=True)

KS = np.arange(1, 21)
N_INPUT, N_HIDDEN, N_OUTPUT, N_DATA = 8, 20, 3, 40
P = N_HIDDEN*N_INPUT + N_HIDDEN + N_OUTPUT*N_HIDDEN + N_OUTPUT
OBSERVERS = ("parameter_fro", "parameter_projection", "latent_fro",
             "latent_projection", "gradient_fro", "output_fro", "loss")

GRID = (
    dict(window=2000, cycles=300.0, max_E=31, kn=20, tau=1, eta=.20),
    dict(window=3000, cycles=600.0, max_E=31, kn=30, tau=2, eta=.20),
    dict(window=4000, cycles=1000.0, max_E=41, kn=40, tau=2, eta=.15),
    dict(window=4000, cycles=1500.0, max_E=41, kn=50, tau=4, eta=.10),
)


def layout(theta):
    q = 0
    W1 = theta[q:q+N_HIDDEN*N_INPUT].reshape(N_HIDDEN, N_INPUT); q += N_HIDDEN*N_INPUT
    b1 = theta[q:q+N_HIDDEN]; q += N_HIDDEN
    W2 = theta[q:q+N_OUTPUT*N_HIDDEN].reshape(N_OUTPUT, N_HIDDEN); q += N_OUTPUT*N_HIDDEN
    b2 = theta[q:q+N_OUTPUT]
    return W1, b1, W2, b2


def forward(theta, X):
    W1, b1, W2, b2 = layout(theta)
    hidden = np.tanh(X@W1.T+b1)
    output = hidden@W2.T+b2
    return output, hidden


def loss_gradient(theta, X, target):
    """MSE and exact gradient with respect to the full parameter vector."""
    W1, b1, W2, b2 = layout(theta)
    output, hidden = forward(theta, X)
    residual = output-target
    doutput = residual/N_DATA
    gW2 = doutput.T@hidden
    gb2 = doutput.sum(axis=0)
    dh = (doutput@W2)*(1.0-hidden*hidden)
    gW1 = dh.T@X
    gb1 = dh.sum(axis=0)
    grad = np.concatenate([gW1.ravel(), gb1, gW2.ravel(), gb2])
    return .5*np.sum(residual*residual)/N_DATA, grad, output


def setup(k, seed):
    rng = np.random.default_rng(71_000+101*k+seed)
    X = rng.standard_normal((N_DATA, N_INPUT))
    X /= np.linalg.norm(X, axis=1, keepdims=True)
    theta0 = .18*rng.standard_normal(P)
    # Generic k-dimensional orientation in the full P-dimensional space.
    U, _ = np.linalg.qr(rng.standard_normal((P, k)), mode="reduced")
    return X, theta0, U


def functional_rank(X, theta0, U, z):
    """Numerical rank of z -> flattened MLP predictions at one point."""
    eps = 1e-5
    cols = []
    for j in range(U.shape[1]):
        yp = forward(theta0+U@(z+eps*np.eye(U.shape[1])[j]), X)[0]
        ym = forward(theta0+U@(z-eps*np.eye(U.shape[1])[j]), X)[0]
        cols.append(((yp-ym)/(2*eps)).ravel())
    singular = np.linalg.svd(np.column_stack(cols), compute_uv=False)
    rank = int(np.sum(singular > singular[0]*1e-8))
    return rank, float(singular[-1]/singular[0])


def simulate(k, seed, cfg):
    W = int(cfg["window"]); burn = 1500; n = W+burn
    eta = float(cfg["eta"])
    rng = np.random.default_rng(72_000+seed)
    X, theta0, U = setup(k, seed)
    t = np.arange(n, dtype=float)
    freq = S.frequencies(k, float(cfg["cycles"]), W, seed=seed,
                         band_mode="matched")
    phase = rng.uniform(0, 2*np.pi, k)
    amp = .65*(.7+.3*rng.random(k))
    centre = .15*rng.standard_normal(k)
    zstar = centre[None, :]+amp[None, :]*np.sin(
        2*np.pi*t[:, None]*freq[None, :]+phase[None, :])

    # The dataset X is fixed. Only its regression targets evolve.
    targets = np.empty((n, N_DATA, N_OUTPUT))
    for j in range(n):
        targets[j] = forward(theta0+U@zstar[j], X)[0]

    zs = np.empty((n, k)); thetas = np.empty((n, P)); grads = np.empty((n, P))
    outputs = np.empty((n, N_DATA*N_OUTPUT)); losses = np.empty(n)
    z = centre.copy()
    for j in range(n):
        theta = theta0+U@z
        loss, gtheta, output = loss_gradient(theta, X, targets[j])
        gz = U.T@gtheta
        zs[j], thetas[j], grads[j] = z, theta, gtheta
        outputs[j], losses[j] = output.ravel(), loss
        z = z-eta*gz

    zs, thetas, grads = zs[burn:], thetas[burn:], grads[burn:]
    outputs, losses = outputs[burn:], losses[burn:]
    rt = np.random.default_rng(73_000+seed).standard_normal(P)
    rz = np.random.default_rng(74_000+seed).standard_normal(k)
    raw = {
        "parameter_fro": np.linalg.norm(thetas, axis=1),
        "parameter_projection": thetas@rt,
        "latent_fro": np.linalg.norm(zs, axis=1),
        "latent_projection": zs@rz,
        "gradient_fro": np.linalg.norm(grads, axis=1),
        "output_fro": np.linalg.norm(outputs, axis=1),
        "loss": losses,
    }
    nrng = np.random.default_rng(75_000+seed)
    result = {}
    for name, x in raw.items():
        standardized = (x-x.mean())/(x.std()+1e-15)
        result[name] = standardized+1e-6*nrng.standard_normal(W)
    rank, condition = functional_rank(X, theta0, U, centre)
    return result, rank, condition


def one_job(cfg_id, k, seed):
    cfg = GRID[cfg_id]
    observers, rank, condition = simulate(k, seed, cfg)
    rows = []
    for name, x in observers.items():
        value = E.mg(x, max_E=int(cfg["max_E"]), k=int(cfg["kn"]),
                     tau=int(cfg["tau"]))
        rows.append(dict(cfg_id=cfg_id, seed=seed, k=k, observer=name,
                         MG=float(value), error=float(value-k),
                         functional_rank=rank, jacobian_ratio=condition, **cfg))
    return rows


def score(g):
    g = g.sort_values("k"); error = g.MG.to_numpy()-g.k.to_numpy()
    inversions = int(np.sum(np.diff(g.MG.to_numpy()) <= 0))
    return dict(mae=float(np.mean(np.abs(error))),
                max_error=float(np.max(np.abs(error))),
                rho=float(spearmanr(g.k, g.MG).statistic), inversions=inversions,
                objective=float(np.mean(np.abs(error))+.15*np.max(np.abs(error))
                                +.15*inversions))


def run_jobs(jobs, workers=4):
    rows = []
    with ProcessPoolExecutor(max_workers=workers) as pool:
        fs = [pool.submit(one_job, *job) for job in jobs]
        for i, future in enumerate(as_completed(fs), 1):
            rows.extend(future.result())
            if i % 20 == 0: print(f"completed {i}/{len(fs)}", flush=True)
    return pd.DataFrame(rows)


def main():
    start = time.time()
    cal = run_jobs([(c, int(k), 0) for c in range(len(GRID)) for k in KS])
    cal.to_csv(OUT/"calibration_raw.csv", index=False)
    summaries = []
    for (obs, cfg), g in cal.groupby(["observer", "cfg_id"]):
        summaries.append(dict(observer=obs, cfg_id=cfg, **score(g)))
    cs = pd.DataFrame(summaries).sort_values(["observer", "objective"])
    cs.to_csv(OUT/"calibration_summary.csv", index=False)
    best = cs.groupby("observer", as_index=False).first()
    best.to_csv(OUT/"best_by_observer.csv", index=False)

    configs = sorted(set(int(x) for x in best.cfg_id))
    held = run_jobs([(c, int(k), seed) for c in configs for seed in (1, 2) for k in KS])
    keep = {(r.observer, int(r.cfg_id)) for _, r in best.iterrows()}
    held = held[[((r.observer, int(r.cfg_id)) in keep) for _, r in held.iterrows()]]
    held.to_csv(OUT/"heldout_raw.csv", index=False)
    summaries = []
    for (obs, seed), g in held.groupby(["observer", "seed"]):
        summaries.append(dict(observer=obs, seed=seed, **score(g)))
    hs = pd.DataFrame(summaries); hs.to_csv(OUT/"heldout_summary.csv", index=False)
    ranking = (hs.groupby("observer", as_index=False)
                 .agg(MAE=("mae", "mean"), max_error=("max_error", "max"),
                      rho=("rho", "mean"), inversions=("inversions", "mean"))
                 .sort_values("MAE"))
    ranking.to_csv(OUT/"observer_ranking.csv", index=False)
    ranks = held[["seed", "k", "functional_rank", "jacobian_ratio"]].drop_duplicates()
    ranks.to_csv(OUT/"functional_rank_check.csv", index=False)

    med = held.groupby(["observer", "k"], as_index=False).MG.median()
    fig, axes = plt.subplots(3, 3, figsize=(13, 11), constrained_layout=True,
                             sharex=True, sharey=True)
    for ax, name in zip(axes.flat, OBSERVERS):
        g = med[med.observer == name]
        ax.plot(KS, KS, "k--", lw=1); ax.plot(g.k, g.MG, "o-", ms=3.2, lw=1.2)
        ax.set(title=name, xlabel="True k", ylabel="MG estimate"); ax.grid(alpha=.22)
    for ax in axes.flat[len(OBSERVERS):]: ax.axis("off")
    fig.suptitle("Full MLP in a known intrinsic subspace", fontsize=14)
    fig.savefig(OUT/"heldout_observers_k20.png", dpi=220)
    fig.savefig(OUT/"heldout_observers_k20.pdf"); plt.close(fig)

    winner = ranking.iloc[0].observer; wm = med[med.observer == winner]
    all_ranks_ok = bool(np.all(ranks.functional_rank == ranks.k))
    report = [
        "# MLP в известном k-мерном подпространстве параметров", "",
        "## Постановка", "",
        f"Использовалась двухслойная MLP с `P={P}` параметрами и фиксированным набором "
        f"из `{N_DATA}` входов. Полный вектор параметров задавался как `theta=theta0+Uz`, "
        "где столбцы `U` ортонормированы, а обучался только `z` размерности `k`.", "",
        "Цели генерировались той же MLP при независимо меняющихся координатах `z*(t)`. "
        "Градиент проходил через оба слоя MLP, после чего проецировался как `U.T grad_theta`. "
        "Следовательно, модель имеет сотни параметров, но ровно `k` доступных направлений "
        "оптимизации.", "",
        f"Проверены `k=1,...,20`. Численный ранг отображения из `z` в предсказания "
        f"совпал с `k` во всех held-out запусках: **{all_ranks_ok}**.", "",
        "Параметры MG выбирались на seed 0 сразу для всех `k`; seeds 1 и 2 были "
        "отложены. Подгонка результата отдельно под каждое `k` не применялась.", "",
        "## Результаты", "",
        "| Наблюдатель | MAE | Макс. ошибка | Spearman rho | Инверсии |",
        "|---|---:|---:|---:|---:|",
    ]
    for _, r in ranking.iterrows():
        report.append(f"| `{r.observer}` | {r.MAE:.3f} | {r.max_error:.3f} | "
                      f"{r.rho:.3f} | {r.inversions:.1f} |")
    report += ["", f"Лучший наблюдатель: **`{winner}`**.", "",
               "| Истинное k | Медиана MG | Ошибка |", "|---:|---:|---:|"]
    for _, r in wm.iterrows():
        report.append(f"| {int(r.k)} | {r.MG:.3f} | {r.MG-r.k:+.3f} |")
    report += ["", "![Сравнение наблюдателей](heldout_observers_k20.png)", "",
               "## Вывод", "",
               "Это наиболее близкий к обычному обучению контроль: нелинейная MLP, "
               "фиксированные входы, MSE и полный backpropagation, но известное число "
               "доступных направлений параметров. Точность восстановления приведена "
               "без коррекции по истинному `k`.", "", f"Время: {time.time()-start:.1f} с."]
    (OUT/"final_report.md").write_text("\n".join(report), encoding="utf-8-sig")
    print(ranking.to_string(index=False)); print("rank check", all_ranks_ok)
    print("outputs", OUT)


if __name__ == "__main__":
    main()
