"""Synthetic systems whose dynamical dimension is known by construction, and the
scalar observers we are allowed to look at them through.

The model is the one in the brief: a diagonal matrix whose entries are all nonzero and
of which only ``k`` move,

    W(t) = diag(b_1 + d_1(t), ..., b_D + d_D(t)),   b_i != 0,
    d_i(t) = a_i sin(2 pi f_i t + phi_i)  for the k active coordinates, 0 otherwise.

Why the true dimension is k, precisely. The state of the moving part is the vector of
phases (theta_1, ..., theta_k) with theta_i = 2 pi f_i t + phi_i. Sampling at integer t,
the closure of the orbit is the closure of the subgroup generated by (f_1, ..., f_k) in
the torus T^k. That closure is all of T^k -- a smooth compact manifold of dimension k --
**if and only if** 1, f_1, ..., f_k are rationally independent. If they are not, the
closure is a lower-dimensional subtorus and the ground truth is not k.

That condition is not decoration. Choosing f_i = c_i / window with integer c_i makes
every sampled orbit periodic, the delay vectors contain exact repeats, the neighbour
distances collapse to the noise floor and the estimate becomes meaningless -- which is
how the first draft of ``../prediction_improved/exp_dimension_of_what.py`` produced a
dimension change with the wrong sign. :func:`resonance_margin` measures how far a
frequency set is from that degeneracy, and every system built here reports it.

Amplitude convention. With b_i != 0 the squared Frobenius norm is

    ||W||_F^2 = sum b_i^2  +  2 sum b_i d_i(t)  +  sum d_i(t)^2,

so for a_i << |b_i| the linear term dominates and the norm is close to a generic linear
functional of the k oscillators. This is exactly why the brief's ``b_i != 0`` matters: at
b_i = 0 the norm would be sum d_i^2, which is invariant under d -> -d and therefore
non-injective on the torus. The default ``amp=0.1`` keeps the linear term dominant; the
sweep over ``amp`` in exp1 checks that the conclusion does not depend on it.
"""

import numpy as np

# Enough rationally independent square-root frequencies for the controlled
# dimension-recovery experiments up to k=20.  The earlier tuple stopped at ten,
# which silently made an extension beyond k=10 impossible.
PRIMES = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
          31, 37, 41, 43, 47, 53, 59, 61, 67, 71)


def frequencies(k, cycles_per_window, window, seed=0, band_mode="matched", band=0.3):
    """k frequencies in cycles per sample, rationally independent with each other and 1.

    ``cycles_per_window`` fixes how much of the torus one estimator window sees, which
    the calibration in ../prediction_improved/exp_dimension_of_what.py section B shows is
    the variable that decides whether any of this works. It is a swept parameter here,
    never a default that happens to be favourable.

    ``band_mode`` decides whether the sweep over k is confounded with bandwidth, and it
    is the single most important design choice in this file:

      ``widening`` -- f_j proportional to sqrt(p_j), the obvious construction. Adding an
        oscillator also adds a HIGHER frequency, so the observable's spectral centroid
        rises with k. Under this construction the one-line roughness ratio
        std(dx)/std(x) recovers the ordering of k with Spearman +1.00, exactly as well as
        any dimension estimator -- because it is reading bandwidth, not dimension. Any
        conclusion drawn from a widening sweep is uninterpretable.

      ``matched`` -- all k frequencies lie in the fixed band [1-band, 1+band] times the
        centre, placed at 2*frac(sqrt(p_j))-1 so that the set is rationally independent
        (sqrt of distinct primes are linearly independent over Q, so no integer
        combination vanishes; equally spaced frequencies would give the exact resonance
        f_0 - 2 f_1 + f_2 = 0 and silently collapse the torus). The spectral centroid and
        the rms frequency are then the same for every k, and roughness has nothing left
        to read.
    """
    rng = np.random.default_rng(seed)
    centre = cycles_per_window / window
    if band_mode == "widening":
        ratios = np.sqrt(np.array(PRIMES[:k], dtype=float))
        ratios = ratios / ratios[0]
        jitter = 1.0 + 0.05 * rng.standard_normal(k)
        return centre * ratios * jitter
    if band_mode != "matched":
        raise ValueError(f"unknown band_mode {band_mode!r}")
    frac = np.sqrt(np.array(PRIMES[:k], dtype=float)) % 1.0
    return centre * (1.0 + band * (2.0 * frac - 1.0))


def resonance_margin(freqs, max_order=3):
    """min |m_0 + sum m_i f_i| over small integer vectors m != 0, in cycles per sample.

    Exact rational dependence would make the nominal dimension wrong, and it is excluded
    by construction: ratios of square roots of distinct primes, times a random jitter,
    are rationally independent, so this quantity is never exactly zero. What it measures
    instead is a *finite-sample* property -- how nearly resonant the frequencies are, and
    therefore how long the orbit takes to fill the torus. Its reciprocal is roughly the
    number of samples needed before the sampled orbit stops looking lower-dimensional
    than it is, which is why it is reported next to every estimate rather than checked
    once and forgotten.
    """
    freqs = np.asarray(freqs, dtype=float)
    k = len(freqs)
    # Full Cartesian enumeration grows as (2*order+1)^k and is impossible for
    # k=20 (even order=2 would require 5^20 vectors).  For higher dimensions
    # use a deterministic bounded Monte-Carlo search over integer relations,
    # augmented with all one- and two-coordinate combinations.  This quantity
    # is only a diagnostic finite-sample resonance margin; it is not used to
    # define the ground-truth dimension, so a conservative approximation is
    # preferable to exhausting memory.
    if k <= 4:
        grid = np.indices([2 * max_order + 1] * k).reshape(k, -1).T - max_order
        grid = grid[np.any(grid != 0, axis=1)]
    else:
        rng = np.random.default_rng(9173 + 37 * k + int(np.sum(freqs * 1e9)) % 100000)
        rows = []
        # Unit vectors and pairwise relations are useful low-order checks.
        for i in range(k):
            for s in (-max_order, -1, 1, max_order):
                v = np.zeros(k, dtype=np.int8); v[i] = s; rows.append(v)
        for i in range(k):
            for j in range(i + 1, k):
                for a in (-2, -1, 1, 2):
                    for b in (-2, -1, 1, 2):
                        v = np.zeros(k, dtype=np.int8); v[i] = a; v[j] = b; rows.append(v)
        n_random = min(200_000, max(20_000, 2_000 * k))
        rows.append(rng.integers(-2, 3, size=(n_random, k), dtype=np.int8))
        grid = np.concatenate([np.asarray(rows[:-1]), rows[-1]], axis=0)
        grid = grid[np.any(grid != 0, axis=1)]
    val = grid @ freqs
    return float(np.min(np.abs(val - np.round(val))))  # distance to the nearest integer


def _base(D, seed):
    """Nonzero diagonal offsets b_i, bounded away from zero."""
    rng = np.random.default_rng(1000 + seed)
    b = 1.0 + 0.25 * rng.standard_normal(D)
    b[np.abs(b) < 0.5] = 0.5 * np.sign(b[np.abs(b) < 0.5] + 1e-12)
    return b


def make_system(mode, k=2, D=64, n=2000, cycles_per_window=10.0, window=300,
                amp=0.1, snr=np.inf, seed=0, band_mode="matched"):
    """Return ``dict(diag=(n, D) array, true_dim=float, active=index array, ...)``.

    ``true_dim`` is the dimension of the closure of the sampled orbit, which is what a
    dimension estimator is entitled to recover. It is NOT always k -- that is the point
    of the controls.
    """
    rng = np.random.default_rng(seed)
    t = np.arange(n)
    b = _base(D, seed)
    diag = np.tile(b, (n, 1))
    active = np.arange(k)
    a = amp * (0.5 + 0.5 * rng.random(k))
    info = {"mode": mode, "band_mode": band_mode, "k": k, "D": D, "n": n, "amp": amp,
            "cycles_per_window": cycles_per_window, "seed": seed,
            "active": active, "resonance": np.nan}

    if mode == "quasiperiodic":
        f = frequencies(k, cycles_per_window, window, seed, band_mode)
        phi = rng.uniform(0, 2 * np.pi, k)
        for j, i in enumerate(active):
            diag[:, i] += a[j] * np.sin(2 * np.pi * f[j] * t + phi[j])
        info.update(true_dim=float(k), resonance=resonance_margin(f), freqs=f)

    elif mode == "sync":
        # k coordinates move, but all from ONE phase: the state is a single angle.
        f = frequencies(1, cycles_per_window, window, seed, band_mode)
        phi = rng.uniform(0, 2 * np.pi)
        for j, i in enumerate(active):
            diag[:, i] += a[j] * np.sin(2 * np.pi * f[0] * t + phi)
        info.update(true_dim=1.0, resonance=resonance_margin(f), freqs=f)

    elif mode == "sync_phased":
        # harder control: one frequency, but a fixed distinct phase per coordinate.
        # Still one angle, so still dimension 1, and it looks much more like k movers.
        f = frequencies(1, cycles_per_window, window, seed, band_mode)
        phi = rng.uniform(0, 2 * np.pi, k)
        for j, i in enumerate(active):
            diag[:, i] += a[j] * np.sin(2 * np.pi * f[0] * t + phi[j])
        info.update(true_dim=1.0, resonance=resonance_margin(f), freqs=f)

    elif mode == "scale_monotone":
        # pure rescaling along a fixed direction: a CURVE, never revisited.
        c = 1.0 + 0.5 * (t / n)
        diag = diag * c[:, None]
        info.update(true_dim=1.0, curve=True)

    elif mode == "scale_periodic":
        f = frequencies(1, cycles_per_window, window, seed, band_mode)
        c = 1.0 + amp * np.sin(2 * np.pi * f[0] * t)
        diag = diag * c[:, None]
        info.update(true_dim=1.0, resonance=resonance_margin(f), freqs=f)

    elif mode == "noise":
        # k independent white sequences: not a manifold, dimension is the embedding one.
        for j, i in enumerate(active):
            diag[:, i] += a[j] * rng.standard_normal(n)
        info.update(true_dim=np.inf)

    elif mode == "noise_smooth":
        # k independent SMOOTH random signals: a k-dimensional stochastic process, but
        # differentiable, so it is not the white-noise case and not a torus either.
        for j, i in enumerate(active):
            w = rng.standard_normal(n)
            kern = np.exp(-0.5 * (np.arange(-60, 61) / 20.0) ** 2)
            sm = np.convolve(w, kern / kern.sum(), mode="same")
            diag[:, i] += a[j] * sm / (sm.std() + 1e-12)
        info.update(true_dim=float(k), smooth_noise=True)

    else:
        raise ValueError(f"unknown mode {mode!r}")

    if np.isfinite(snr):
        diag = diag + (amp / snr) * rng.standard_normal(diag.shape)
    info["snr"] = snr
    info["diag"] = diag
    return info


# ---------------------------------------------------------------------- transitions

def make_transition(schedule, D=64, seg=1200, cycles_per_window=10.0, window=300,
                    amp=0.1, snr=np.inf, seed=0, ramp=0, band_mode="matched"):
    """Concatenate regimes of known dimension into one non-stationary series.

    ``schedule`` is e.g. ``[1, 2, 3, 4, 3, 2]``. Each active oscillator keeps its own
    frequency and phase across the whole run, so a dimension change is an amplitude
    switching on or off, not a discontinuity in the signal. With ``ramp > 0`` the switch
    is linear over that many samples, and the ground truth is undefined inside it -- an
    oscillator whose amplitude is below the noise floor is not a degree of freedom the
    data contains, whatever the nominal schedule says.
    """
    rng = np.random.default_rng(seed)
    k_max = max(schedule)
    n = seg * len(schedule)
    t = np.arange(n)
    b = _base(D, seed)
    diag = np.tile(b, (n, 1))
    f = frequencies(k_max, cycles_per_window, window, seed, band_mode)
    phi = rng.uniform(0, 2 * np.pi, k_max)
    a = amp * (0.5 + 0.5 * rng.random(k_max))

    envelope = np.zeros((n, k_max))
    for s, k in enumerate(schedule):
        envelope[s * seg:(s + 1) * seg, :k] = 1.0
    if ramp > 0:
        kern = np.ones(ramp) / ramp
        for j in range(k_max):
            envelope[:, j] = np.convolve(envelope[:, j], kern, mode="same")

    for j in range(k_max):
        diag[:, j] += a[j] * envelope[:, j] * np.sin(2 * np.pi * f[j] * t + phi[j])
    if np.isfinite(snr):
        diag = diag + (amp / snr) * rng.standard_normal(diag.shape)

    truth = np.repeat(np.asarray(schedule, dtype=float), seg)
    return {"diag": diag, "truth": truth, "schedule": schedule, "seg": seg,
            "freqs": f, "resonance": resonance_margin(f), "n": n,
            "cycles_per_window": cycles_per_window, "ramp": ramp, "seed": seed,
            "snr": snr}


# ------------------------------------------------------------------------ observers

def observers(info, n_random=4, seed=0, obs_snr=1e4):
    """Scalar series from the (n, D) diagonal trajectory.

    Three groups, and the grouping is a prediction, not a result:

      * expected good -- functions that mix all the active coordinates with generic
        coefficients, so the induced map on the torus is injective for a generic choice;
      * expected bad by construction -- functions of a strict subset of the angles. The
        true dimension OF THE IMAGE is then lower than k, so a low reading here is the
        estimator being right about a lossy observer, not the estimator failing;
      * expected degenerate -- constants, where no estimate is defined.

    An estimator that returns k on an 'expected bad by construction' observer is not
    conservative, it is hallucinating.

    Every series is standardised and then given measurement noise at ``1/obs_snr`` of its
    own spread. Standardising costs nothing -- the W=0 estimate is scale invariant -- and
    it makes the signal-to-noise ratio the same number for every observer and every k.
    Without it the comparison is rigged: at fixed per-coordinate noise a single
    oscillator moves the Frobenius norm least, so k=1 has the worst SNR of the sweep and
    reads *higher* than k=2, purely as a noise-floor artefact. That inversion is real and
    is what this normalisation removes.
    """
    diag, active = info["diag"], np.asarray(info["active"])
    n, D = diag.shape
    rng = np.random.default_rng(7000 + seed)
    inactive = np.setdiff1d(np.arange(D), active)
    out = {}

    out["norm_fro"] = np.linalg.norm(diag, axis=1)
    out["norm_fro_sq"] = (diag ** 2).sum(axis=1)
    out["trace"] = diag.sum(axis=1)
    out["logdet"] = np.log(np.abs(diag) + 1e-12).sum(axis=1)
    out["norm_l1"] = np.abs(diag).sum(axis=1)
    for j in range(n_random):
        r = rng.standard_normal(D)
        out[f"proj_rand{j}"] = diag @ r

    if len(active):
        out["coord_active0"] = diag[:, active[0]].copy()
        sub = active[:max(1, len(active) // 2)]
        w = np.zeros(D)
        w[sub] = rng.standard_normal(len(sub))
        out["proj_half_active"] = diag @ w
    if len(inactive):
        out["coord_inactive"] = diag[:, inactive[0]].copy()
        w = np.zeros(D)
        w[inactive] = rng.standard_normal(len(inactive))
        out["proj_inactive_only"] = diag @ w

    for name, series in out.items():
        s = np.std(series)
        z = (series - np.mean(series)) / s if s > 0 else np.zeros_like(series)
        out[name] = z + (1.0 / obs_snr) * rng.standard_normal(n)
    return out


def image_dimension(name, k):
    """True dimension of the observable's image -- what the estimator should return.

    For an observable that mixes every active angle with generic coefficients this is k.
    For one that sees a strict subset it is the size of that subset, and a low reading is
    then the estimator being correct about a lossy observer rather than failing.
    """
    if name in ("coord_active0",):
        return 1.0
    if name in ("proj_half_active",):
        return float(max(1, k // 2))
    if name in ("coord_inactive", "proj_inactive_only"):
        return np.nan                                  # pure noise: no manifold
    return float(k)


EXPECTED = {
    "norm_fro": "good", "norm_fro_sq": "good", "trace": "good", "logdet": "good",
    "norm_l1": "good", "proj_rand0": "good", "proj_rand1": "good",
    "proj_rand2": "good", "proj_rand3": "good",
    "coord_active0": "bad_by_construction",       # one angle -> image is a circle
    "proj_half_active": "bad_by_construction",    # floor(k/2) angles
    "coord_inactive": "degenerate",               # constant + noise
    "proj_inactive_only": "degenerate",           # constant + noise
}
