"""Shape-preserving surrogates: the same spectrum and the same values, different phases.

An IAAFT surrogate keeps the power spectrum -- and with it the autocorrelation, the roughness
and every smoothness statistic -- and the amplitude distribution, while destroying the phase
relations that make a signal deterministic. If the estimate on a record equals the estimate on
its surrogates, then the estimate is a function of the power spectrum and carries nothing
about geometry, however well it correlates with the truth.

It is the right null for the article's real training logs, where the alternative explanation
is smoothness. It is the wrong null for a quasiperiodic system: randomising the phases of an
r-torus leaves an r-torus, since every line stays in the module generated by the r drive
frequencies, so the test would compare determinism against a linear Gaussian process rather
than r directions against a broader spectrum. The spectral participation ratio of
``companions`` is the null that answers that question.

**One implementation, where the archived tree had two under one name.** ``mg.iaaft`` ran 12
iterations and matched endpoints; ``e10_surrogate.iaaft`` ran 100 and did not. What is kept
here: **endpoint matching on by default, and the iteration count an argument defaulting to
100**. Matching is kept because the failure it avoids is measured and large -- a Fourier
surrogate treats the window as one period, so ends that do not match imply a jump, the jump
leaks broadband power across the whole spectrum, and randomising those phases manufactures
noise that was never in the data. On a pure sinusoid, whose surrogate must still be a 1-torus
with an estimate near 2, the unmatched surrogate reads 4.3. The higher iteration count is kept
because 12 is not converged and the cost is trivial.

Matching trims the series to the sub-window whose ends agree, so the surrogate is shorter than
its original by up to 15 %. That is why the archived matched-window control ran unmatched: it
paired each surrogate with the observed record's window grid, and a shorter series would have
shifted that grid. A pipeline that needs the original length must pass ``match=False``, which
reproduces that control exactly.
"""
from __future__ import annotations

from typing import Any, Dict, Optional

import numpy as np

from .config import EstimatorConfig
from .windows import summarise


def match_endpoints(x: np.ndarray, min_frac: float = 0.85) -> np.ndarray:
    """Trim to the sub-series whose ends agree best in value and in slope.

    Searches only the last ``1 - min_frac`` of the record, so at most 15 % is given up. Cost
    is the endpoint mismatch in value and in first difference, each in units of its own
    spread, so neither dominates by being measured in larger numbers.
    """
    x = np.asarray(x, dtype=np.float64)
    n = len(x)
    lo = int(n * min_frac)
    if lo >= n - 2:
        return x
    diff = np.diff(x)
    spread = np.std(x) + 1e-30
    spread_diff = np.std(diff) + 1e-30
    cost = (np.abs(x[:n - lo] - x[lo - 1:n - 1]) / spread
            + np.abs(diff[:n - lo] - diff[lo - 2:n - 2]) / spread_diff)
    return x[:lo + int(np.argmin(cost))]


def iaaft(x: np.ndarray, iters: int = 100, rng: Optional[np.random.Generator] = None,
          match: bool = True) -> np.ndarray:
    """One iterative amplitude-adjusted Fourier-transform surrogate.

    Alternates two projections -- impose the original amplitude spectrum, then impose the
    original sorted values -- from a random shuffle. Neither projection is onto a convex set,
    so the iteration is not guaranteed to converge and is simply run a fixed number of times;
    ``iters`` is an argument so that a caller can say how many, which the archived code could
    not without editing the function.
    """
    rng = np.random.default_rng(0) if rng is None else rng
    x = np.asarray(x, dtype=np.float64)
    if match:
        x = match_endpoints(x)
    n = len(x)
    if n < 4:
        return x.copy()
    sorted_values = np.sort(x)
    amplitude = np.abs(np.fft.rfft(x))
    y = rng.permutation(x)
    for _ in range(int(iters)):
        spectrum = np.fft.rfft(y)
        y = np.fft.irfft(amplitude * np.exp(1j * np.angle(spectrum)), n=n)
        y = sorted_values[np.argsort(np.argsort(y))]
    return y


def surrogate_summary(x: np.ndarray, cfg: EstimatorConfig, n: int = 3, seed: int = 0,
                      rng: Optional[np.random.Generator] = None, iters: int = 100,
                      match: bool = True) -> Dict[str, Any]:
    """Median estimate over ``n`` surrogates of one record, and the spread across them.

    ``rng`` draws the surrogates and ``seed`` dithers them; they are separate because the
    dither must be the same for the record and its surrogates while the surrogates must
    differ from each other. Pass ``ctx.rng("surrogate")`` for the first, so that a second
    process reproduces the same set.
    """
    rng = np.random.default_rng(seed) if rng is None else rng
    values = []
    for _ in range(int(n)):
        surrogate = iaaft(x, iters=iters, rng=rng, match=match)
        values.append(summarise(surrogate, cfg, seed=seed)["MG"])
    finite = np.asarray(values, dtype=np.float64)
    finite = finite[np.isfinite(finite)]
    if not len(finite):
        return {"MG_surr": float("nan"), "MG_surr_sd": float("nan"), "n_surr": 0}
    return {"MG_surr": float(np.median(finite)), "MG_surr_sd": float(finite.std()),
            "n_surr": int(len(finite))}
