"""One place where a Spec becomes a row of measurements, so every experiment measures the
same things the same way.

A run produces, for each of the 16 observers, every estimator in ``mg.ESTIMATOR_NAMES`` at
two embedding dimensions.  The second one exists only for the identifiability ratio
``E(2 max_E) / E(max_E)``: near 1 the estimate is a property of the data, near 2 it is a
property of the embedding space and no dimension is identifiable at this sample size.  The
diagnostic is in the project's own package (``edm.dimension.identifiability_ratio``) and no
experiment in ``dimension_recovery`` ever called it; on the exp13/14 systems it is 1.30-1.33
at k=20, which is exactly where those experiments' errors grow.

Ground truth is always the **measured** active dimension (``traj_PR``), never the nominal r
and never the available k.
"""

from __future__ import annotations

import dataclasses

import numpy as np

import mg as MG
from dynamics import OBSERVERS, OBSERVER_FAMILY, Spec, equalise_gains, simulate
from system import build, rank_pr

_CACHE = {}


def get_system(seed, k=10):
    key = (seed, k)
    if key not in _CACHE:
        A = build(seed=seed, k=k)
        _CACHE[key] = (A, A.solve())
    return _CACHE[key]


#: the identifiability ratio needs a second, doubled embedding; computing it for all 16
#: observers doubles-to-quadruples the cost of the sweep, so it is computed for one observer
#: per family, which is enough to say whether a dimension is identifiable at all.
IDENT_OBS = ("w_fro", "g_fro", "c_proj1")


def run_one(spec: Spec, cfg: MG.MGConfig, second_E=True, observers=OBSERVERS,
            keep_traces=False, n_surrogate=0):
    """Simulate, then measure.  Returns (rows, info, traces).

    ``n_surrogate`` defaults to 0.  A phase-randomised surrogate is the wrong null for a
    quasi-periodic system -- every line of an r-torus stays in the module generated by
    f_1..f_r, so randomising the phases leaves an r-torus, and what the test actually
    measures is spectral leakage (measured: MG = 4.3 on the surrogate of a pure sinusoid,
    where 2 is correct).  ``mg.spectral_pr`` is the null that answers the question instead.
    The surrogate machinery is kept because it *is* the right null for the stochastic arms.
    """
    A, c_star = get_system(spec.seed, spec.k)
    mix, cond = equalise_gains(A, spec, c_star)
    logs, C, D, info = simulate(A, spec, c_star=c_star, mix=mix)
    info["drive_cond"] = cond

    cfg2 = dataclasses.replace(cfg, max_E=2 * cfg.max_E) if second_E else None
    rows, traces = [], {}
    for o in observers:
        x = logs[o]
        s = x.std()
        base = dict(observer=o, family=OBSERVER_FAMILY[o], obs_sd=float(s))
        if not np.isfinite(x).all() or s <= 1e-12:
            rows.append({**base, **{n: np.nan for n in MG.ESTIMATOR_NAMES}, "flat": True})
            continue
        z = (x - x.mean()) / s                    # z-scored: MG is scale-invariant anyway,
        rec = MG.summarise(z, cfg)                # but this equalises the dither's effect
        rec = {**base, **rec, "flat": False}
        if cfg2 is not None and o in IDENT_OBS:
            rec["MG_2E"] = MG.summarise(z, cfg2)["MG"]
            rec["ident_ratio"] = rec["MG_2E"] / rec["MG"] if rec["MG"] else np.nan
        if n_surrogate:
            rec.update(MG.surrogate_summary(z, cfg, n=n_surrogate, seed=spec.seed))
            rec["MG_excess"] = rec["MG"] - rec["MG_surr"]
        rows.append(rec)
        if keep_traces:
            traces[o] = MG.sliding(z, cfg)
    return rows, info, traces


def spec_columns(spec: Spec):
    return {a: b for a, b in dataclasses.asdict(spec).items() if not isinstance(b, np.ndarray)}


def flatten(spec: Spec, rows, info):
    sc = spec_columns(spec)
    return [{**sc, **info, **r} for r in rows]


# ------------------------------------------------------------------ scoring helpers
def spearman(a, b):
    from scipy.stats import spearmanr
    a, b = np.asarray(a, float), np.asarray(b, float)
    ok = np.isfinite(a) & np.isfinite(b)
    if ok.sum() < 3 or np.unique(a[ok]).size < 2 or np.unique(b[ok]).size < 2:
        return np.nan
    return float(spearmanr(a[ok], b[ok]).statistic)


def mae(a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    ok = np.isfinite(a) & np.isfinite(b)
    return float(np.mean(np.abs(a[ok] - b[ok]))) if ok.any() else np.nan
