"""E10: model selection for learned simulators (dynamical systems reconstruction) by MG.

An echo state network (ESN) is trained by ridge regression to predict the next value of a
scalar series generated by a known system, then run in closed loop. Many hyperparameter
settings give a small one-step error yet the wrong long-run dynamics: the torus locks into
a cycle, the model decays to a point, or it turns chaotic. The practitioner's question:
which trained model to keep, using only the scalar series it generates.

Ground truth (expensive, uses the full model): the Lyapunov spectrum of the closed-loop map
plus a frequency/amplitude check of the generated series.
Selectors (cheap, scalar only): one-step validation error, valid prediction time, the
spectral Hellinger distance D_H of the DSR literature, and |stat(model) - stat(data)| for
MG and every competitor in baselines.py.

PROTOCOL (frozen after the pilot on T2, dseed 0, which looked only at the Lyapunov
classes, never at a selector; MG config chosen in calib_dsr.py on target signals only).

Confirmatory run: targets T2, T3 (tori, base period 40.37 steps, clean data) and Lorenz x
(dt 0.02); data seeds 1-3, reservoir seed 0 for every data seed; the 162-point grid over spectral
radius, input scale, leak and ridge; N = 300.

Ground truth "faithful", from the full model:
  torus Tq  output std within x[0.5, 2] of the data, lambda1 <= 0.003 per step, exactly q
            exponents >= -0.003 among the top six, and each true frequency within 1.5 %
            of one of the six strongest spectral peaks of the output;
  Lorenz    std within x[0.5, 2], lambda1 within [0.5, 1.5] x 0.0181 per step, and lambda2
            within +-0.003 (the zero exponent).
Candidate pool for every selector: models whose output is finite and whose std is within
x[0.5, 2] of the data (a check any practitioner makes).
Selectors: one-step validation MSE (min), valid prediction time (max), spectral Hellinger
distance D_H (min), and |s(model) - s(data)| (min) for s in MG, spectral entropy, self-repeat,
roughness, peak count, permutation entropy, recurrence rate, correlation dimension,
TwoNN, linear PR. All use only the scalar output.
Scores per (target, data seed): top-1 faithful, precision among the 5 best, AUC of
faithful vs unfaithful within the pool.
Predictions:
  P1  MG's mean AUC >= 0.8 and exceeds those of MSE, VPT and D_H;
  P2  MG's mean top-5 precision exceeds those of MSE, VPT and D_H;
  P3  MG picks a faithful model (top-1) in at least 7 of the 9 problems.
The geometric competitors (recurrence rate, correlation dimension, TwoNN) are reported
without a prediction.
"""
from __future__ import annotations

import os
for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ[_v] = "1"

import argparse
import json
import sys
import time
from itertools import product
from multiprocessing import Pool
from pathlib import Path

import numpy as np
from scipy.integrate import solve_ivp
from threadpoolctl import threadpool_limits

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import baselines as BL  # noqa: E402

OUT = HERE / "results_esn"
L_TRAIN, L_VAL, L_RUN, BURN, L_LYAP = 12000, 3000, 8192, 2000, 6000
PERIOD, NOISE = 40.37, 0.0
# chosen in calib_dsr.py on target signals only
from functools import partial
from actdim.estimator.config import EstimatorConfig
CFG_MG = EstimatorConfig(max_E=20, tau="acorr", k_neighbors=50, theiler="autocorr", theiler_cap=320)
BL.ALL["MG"] = partial(BL.mg, cfg=CFG_MG)


# ---------------------------------------------------------------- target systems ---------

def torus(n, q, seed, period=PERIOD, noise=NOISE):
    """Observed scalar of a q-torus: nonlinear mix of q phases, frequency ratios golden/irrational."""
    rng = np.random.default_rng(100 + seed)
    w = np.array([1.0, (1 + 5 ** .5) / 2, 2 ** .5 + 1.0, 3 ** .5 * 1.37][:q]) * 2 * np.pi / period
    ph = rng.uniform(0, 2 * np.pi, q)
    t = np.arange(n)
    P = np.outer(t, w) + ph
    amp = np.array([1.0, 0.8, 0.6, 0.5][:q])
    x = (amp * np.cos(P)).sum(1)
    if q >= 2:
        x += 0.3 * np.cos(P[:, 0]) * np.cos(P[:, 1])
    x = x + noise * x.std() * rng.normal(size=n)
    return x, {"kind": "torus", "q": q, "freqs": (w / (2 * np.pi)).tolist()}


def lorenz(n, seed, dt=0.02):
    rng = np.random.default_rng(200 + seed)
    f = lambda t, s: [10 * (s[1] - s[0]), s[0] * (28 - s[2]) - s[1], s[0] * s[1] - 8 / 3 * s[2]]
    s0 = rng.normal(size=3) + [1, 1, 20]
    tt = np.arange(n + 2000) * dt
    sol = solve_ivp(f, (0, tt[-1]), s0, t_eval=tt, rtol=1e-9, atol=1e-9)
    x = sol.y[0, 2000:]
    return x + NOISE * x.std() * rng.normal(size=n), {"kind": "lorenz", "lyap1_per_step": 0.906 * dt, "dt": dt}


def target(name, n, seed):
    if name.startswith("T"):
        return torus(n, int(name[1:]), seed)
    if name == "lorenz":
        return lorenz(n, seed)
    raise ValueError(name)


# ---------------------------------------------------------------- ESN ----------------------

def esn_init(seed, N, rho, sin, density=0.05):
    rng = np.random.default_rng(seed)
    W = rng.normal(size=(N, N)) * (rng.random((N, N)) < density)
    W *= rho / np.max(np.abs(np.linalg.eigvals(W)))
    return W, rng.uniform(-sin, sin, N), rng.uniform(-0.2, 0.2, N)


def run_driven(W, win, b, a, u):
    N = len(b)
    r = np.zeros(N)
    R = np.empty((len(u), N))
    for t, ut in enumerate(u):
        r = (1 - a) * r + a * np.tanh(W @ r + win * ut + b)
        R[t] = r
    return R


def fit(R, y, beta):
    X = np.hstack([R, np.ones((len(R), 1))])
    return np.linalg.solve(X.T @ X + beta * np.eye(X.shape[1]), X.T @ y)


def closed_loop(W, win, b, a, wout, r, x, n, lyap_steps=0, k=6, seed=0):
    N = len(b)
    out = np.empty(n)
    wr, w0 = wout[:-1], wout[-1]
    if lyap_steps:
        Q = np.linalg.qr(np.random.default_rng(seed).normal(size=(N, k)))[0]
        logs = np.zeros(k); m = 0
    for t in range(n):
        pre = W @ r + win * x + b
        r_new = (1 - a) * r + a * np.tanh(pre)
        if lyap_steps and t < lyap_steps:
            # Jacobian of r -> r_new with x = wout.r fed back
            g = a * (1 - np.tanh(pre) ** 2)
            JQ = (1 - a) * Q + g[:, None] * (W @ Q + np.outer(win, wr @ Q))
            Q, Rq = np.linalg.qr(JQ)
            if t >= 500:
                logs += np.log(np.abs(np.diag(Rq)) + 1e-300); m += 1
        r = r_new
        x = wr @ r + w0
        out[t] = x
        if not np.isfinite(x) or abs(x) > 1e3:
            out[t:] = np.nan
            break
    lyap = np.sort(logs / max(m, 1))[::-1] if lyap_steps else None
    return out, r, lyap


def vpt(W, win, b, a, wout, R_val, u_val, thr=0.3, starts=10, horizon=400):
    """Valid prediction time: steps of closed-loop forecast before NRMSE exceeds thr (median)."""
    s = np.std(u_val)
    res = []
    for i in np.linspace(200, len(u_val) - horizon - 2, starts).astype(int):
        pred, _, _ = closed_loop(W, win, b, a, wout, R_val[i].copy(), u_val[i + 1], horizon)
        err = np.abs(pred - u_val[i + 2:i + 2 + horizon]) / s
        bad = np.where(~(err < thr))[0]
        res.append(bad[0] if len(bad) else horizon)
    return float(np.median(res))


def spectrum(x, nseg=1024):
    from scipy.signal import welch
    f, P = welch(x - x.mean(), nperseg=nseg)
    return P / P.sum()


def hellinger(x, y):
    p, q = spectrum(x), spectrum(y)
    return float(np.sqrt(max(0.0, 1 - np.sum(np.sqrt(p * q)))))


# ---------------------------------------------------------------- one model ---------------

GRID = {"rho": [0.4, 0.7, 0.9, 1.0, 1.1, 1.3], "sin": [0.1, 0.5, 1.5], "a": [0.2, 0.5, 1.0],
        "beta": [1e-8, 1e-5, 1e-2]}


def one(args):
    tname, dseed, rseed, hp, N = args
    rho, sin, a, beta = hp
    t0 = time.perf_counter()
    u, meta = target(tname, L_TRAIN + L_VAL + L_RUN + 1, dseed)
    mu, sd = u[:L_TRAIN].mean(), u[:L_TRAIN].std()
    u = (u - mu) / sd
    W, win, b = esn_init(1000 * rseed + 7, N, rho, sin)
    R = run_driven(W, win, b, a, u[:L_TRAIN + L_VAL])
    wout = fit(R[300:L_TRAIN], u[301:L_TRAIN + 1], beta)
    X = np.hstack([R, np.ones((len(R), 1))])
    pred1 = X[L_TRAIN:L_TRAIN + L_VAL - 1] @ wout
    mse1 = float(np.mean((pred1 - u[L_TRAIN + 1:L_TRAIN + L_VAL]) ** 2))
    v = vpt(W, win, b, a, wout, R[L_TRAIN:], u[L_TRAIN:L_TRAIN + L_VAL])
    run, _, lyap = closed_loop(W, win, b, a, wout, R[L_TRAIN + L_VAL - 1].copy(), u[L_TRAIN + L_VAL - 1],
                               BURN + L_RUN, lyap_steps=L_LYAP)
    gen = run[BURN:]
    data = u[L_TRAIN + L_VAL:L_TRAIN + L_VAL + L_RUN]
    row = {"target": tname, "dseed": dseed, "rseed": rseed, "rho": rho, "sin": sin, "a": a,
           "beta": beta, "N": N, "mse1": mse1, "vpt": v, "lyap": lyap.round(5).tolist(),
           "diverged": bool(not np.all(np.isfinite(gen))), "std_ratio": float(np.nanstd(gen))}
    if not row["diverged"] and np.std(gen) > 1e-3:
        row["D_H"] = hellinger(gen, data)
        for name, fn in BL.ALL.items():
            try:
                row[name] = float(fn(gen))
            except Exception:
                row[name] = np.nan
        f, P = np.fft.rfftfreq(len(gen)), np.abs(np.fft.rfft((gen - gen.mean()) * np.hanning(len(gen)))) ** 2
        row["peak_freqs"] = f[np.argsort(P)[::-1][:12]].tolist()
    row["t"] = time.perf_counter() - t0
    return row


def data_stats(tname, dseed):
    u, meta = target(tname, L_TRAIN + L_VAL + L_RUN + 1, dseed)
    x = (u[-L_RUN:] - u[:L_TRAIN].mean()) / u[:L_TRAIN].std()
    return {"target": tname, "dseed": dseed, "meta": meta, **{k: float(f(x)) for k, f in BL.ALL.items()}}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--targets", nargs="+", default=["T2"])
    ap.add_argument("--dseeds", type=int, nargs="+", default=[0])
    ap.add_argument("--rseeds", type=int, nargs="+", default=[0])
    ap.add_argument("--N", type=int, default=300)
    ap.add_argument("--procs", type=int, default=12)
    ap.add_argument("--tag", default="pilot")
    args = ap.parse_args()
    OUT.mkdir(exist_ok=True)
    jobs = [(t, d, r, hp, args.N) for t in args.targets for d in args.dseeds for r in args.rseeds
            for hp in product(*GRID.values())]
    print(len(jobs), "models", flush=True)
    with threadpool_limits(1), Pool(args.procs) as p:
        ds = [data_stats(t, d) for t in args.targets for d in args.dseeds]
        json.dump(ds, open(OUT / f"data_{args.tag}.json", "w"), indent=1)
        rows = []
        for i, r in enumerate(p.imap_unordered(one, jobs, chunksize=2)):
            rows.append(r)
            if i % 50 == 0:
                print(i, f"{r['t']:.1f}s", flush=True)
                json.dump(rows, open(OUT / f"models_{args.tag}.json", "w"), default=float)
    json.dump(rows, open(OUT / f"models_{args.tag}.json", "w"), default=float)
    print("done", flush=True)


if __name__ == "__main__":
    main()
