"""Recompute the article's tables from ``data/`` and diff them against the printed LaTeX.

The article has now failed a release check twice for the same reason: a committed script
could no longer regenerate the file a table was quoting. The archived tree carried one
narrow guard against that, ``active_dimension/paper_tables.py``, covering two tables. This
generalises it to the whole document.

The check is one-directional and deliberately dumb. It reads ``icomp_v2/report.tex``,
recomputes every cell it knows how to recompute from a file under ``data/``, and reports
the pairs that disagree at the precision the article prints. It never edits the article and
never writes a file: it returns a report and the caller decides what to do with it.

Rounding is respected rather than approximated. A printed ``1.62`` matches a computed
1.6239 and does not match 1.554, because the comparison rounds the computed value to the
number of decimals actually printed. A cell that is out by no more than one unit in that
last place is reported separately as ``rounding``: the measurement agrees and the digits do
not, which is a typesetting defect rather than a data defect. Both count as mismatches for
the exit status, because either way the article prints something the file does not say.

Beside the cells the module checks *claims*: statements a caption or the surrounding text
makes that ``data/`` can settle. Three of the defects already on record are of that shape
rather than the shape of a wrong cell, and a checker that only compared cells would pass
all three.

Where the inputs came from
--------------------------

Every file read is looked up in ``data/manifest.json`` and the report says whether it was
regenerated by this package or seeded from ``../archived_code``. Today all ninety-three are
archived, so every table below has been checked against the numbers the article was written
from and not against a regeneration. That is the weaker of the two statements and it is what
the report prints.

What is checked
---------------

Twenty-one of the twenty-eight ``tabular`` blocks have at least one column derivable from
``data/``:

``tab:frozen``      the two frozen configurations, against the two ``frozen_*.json`` and the
                    eight-direction grid. The twenty-direction grid was not promoted, so
                    that column's grid size and selection errors are unchecked.
``tab:geometry``    the frozen row only; the other two rows state a convention.
``tab:ladder``      error and rank correlation, one system per row, recomputed from
                    ``heldout_raw.csv`` and cross-read against ``observer_ranking.csv``.
``tab:aggregation`` all three errors, each recomputed by its own stated recipe.
``tab:obs``         error, slope, and whether roughness orders the four withheld ranks.
``tab:k20``         every cell. Ported from the archived checker.
``tab:alts``        every cell, and the aggregation asymmetry below. Ported.
``tab:tau``         span and the estimate at every lag and rank.
``tab:controls``    the shift and its percentage of a four-component change, and the
                    caption's two omissions against ``calib.e20/invariance_controls.csv``.
``tab:switch``      the three levels of each schedule.
``tab:aniso``       effective rank, MG and the delay participation ratio.
``tab:gt``          the excited rank of every regime.
``tab:grok-diagnostics``  whether each run generalises, and its five diagnostics.
``tab:dip``         plateau, dip, depth, position and post-dip maximum.
``tab:prwindow``    every row but the 600-step one, which the caption says is the earlier
                    measurement and not part of the sweep the file holds.
``tab:matched``     depth, floor and the three surrogate fractions. The quantile column
                    names a statistic no committed file records.
``tab:theiler``     truth and both exclusions, the two summary rows, and the label of the
                    error row.
``tab:runs``        budget, weight decay and training fraction for all twenty-seven rows,
                    from the run registry; memorisation, generalisation and final accuracy
                    for the six sketched rows against both the summary and the milestone
                    file, and memorisation and generalisation for the seven extended ones
                    against the outcome file. See below.
``tab:eos``         stability ratio, rises and return, per seed.
``tab:ceiling``     both scans -- tracking, the prediction, the level and the slope -- and
                    the cell the two scans share.
``tab:ceilingfit``  the four root-mean-square errors.

What is not, and why
--------------------

``tab:classes``, ``tab:obsdef``  definitions. Nothing to recompute.
``tab:geometry`` rows 2-3       a convention, stated rather than measured.
``tab:obsdep``   no file under ``data/`` scores the two mode-weightings at several lags.
``tab:sketch``   the per-rank sketched and uncompressed participation ratios were never
                 promoted; ``check.sketch.cost/sketch_cost.json`` records only time and
                 storage, which the table does not print.
``tab:exclusion`` the recipe is not recoverable. The caption says "median over observers,
                 seeds and windows" of ``valid.theiler.contrast/sweep_windows.csv``; taking
                 that literally gives 5.43 / 2.07 / 1.20 in the first column against a
                 printed 5.39 / 2.11 / 1.20, and collapsing in a different order moves every
                 cell again without landing on the printed values. Four of its cells would
                 match under two different orders and the rest under neither, so a guess
                 here would report noise rather than defects.
``tab:ipr``, ``tab:ipr-trajectory``  the Fourier inverse participation ratio outputs are not
                 in ``data/``. The grokking-step column of ``tab:ipr`` repeats ``tab:runs``,
                 whose perceptron milestones have no measured source either.

Two further gaps are inside tables that are otherwise checked. ``tab:runs``'s thirteen
perceptron rows have no committed log, so their milestone columns are compared against the
registry's transcription of the table rather than against a measurement; and the sentence
below that table, that the sketched runs agree with the rows above to within one or two
logged steps, needs the milestones of two campaigns that were never promoted.

The aggregation asymmetry, carried forward from the archived checker
--------------------------------------------------------------------

``tab:alts``'s two halves are not the same measurement at two ranges, and the caption does
not say so:

* the eight-direction column scores the four *withheld* ranks 1, 3, 5, 8 of the parameter
  sweep, which is the convention the appendix D preamble states;
* the twenty-direction column scores **all twenty** ranks of the k20 calibration, the five
  ranks the configuration was selected on included.

Restricting the twenty-direction side to the ten ranks ``tab:k20`` prints gives MG 1.554,
not the printed 1.62. The check computes it both ways, so the size of the difference is a
number this module produces rather than a claim in a comment.

Reading the report
------------------

    from actdim.tables import audit, format_report
    report = audit()
    print(format_report(report))

or from the command line, which exits non-zero on any mismatch::

    python -m actdim.tables
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
from dataclasses import dataclass, field
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

from .runtime.store import data_root, load_manifest, repo_root


# ---------------------------------------------------------------- where things live

def article_path() -> Path:
    """``icomp_v2/report.tex``, wherever the working directory is."""
    return repo_root().parent / "icomp_v2" / "report.tex"


# ---------------------------------------------------------------- the LaTeX reader

_RULES = ("\\toprule", "\\midrule", "\\bottomrule", "\\cmidrule", "\\addlinespace",
          "\\morecmidrules", "\\hline")

# Macros whose braced argument is the text, and which contribute nothing else.
_UNWRAP = ("texttt", "textbf", "textit", "emph", "mathrm", "mathit", "text", "operatorname",
           "cref", "Cref", "ref", "label", "multirow", "boldmath")

_ESCAPES = (("\\_", "_"), ("\\&", "&"), ("\\%", "%"), ("\\#", "#"), ("\\{", "{"),
            ("\\}", "}"), ("\\$", "$"))

_THIN = ("\\,", "\\!", "\\;", "\\:", "\\/")
_SPACES = ("\\quad", "\\qquad", "\\ ", "~", "\\hspace")

_MISSING = ("---", "--", "\u2014", "\u2013")


def _strip_rules(text: str) -> str:
    for rule in _RULES:
        text = re.sub(re.escape(rule) + r"(\([a-z]{1,2}\))?(\{[^}]*\})?", "", text)
    return text


class ParseError(RuntimeError):
    """A table this reader will not guess at."""


@dataclass
class Cell:
    """One cell, cleaned of the formatting macros this document uses."""

    text: Optional[str]          # None where the article prints a dash
    raw: str
    column: int                  # first logical column this cell covers
    span: int = 1

    @property
    def missing(self) -> bool:
        return self.text is None


@dataclass
class Row:
    cells: List[Cell]
    line: int

    def at(self, column: int) -> Optional[Cell]:
        for cell in self.cells:
            if cell.column <= column < cell.column + cell.span:
                return cell
        return None

    def label(self) -> str:
        for cell in self.cells:
            if cell.text:
                return cell.text
        return ""

    @property
    def width(self) -> int:
        return sum(cell.span for cell in self.cells)


@dataclass
class Table:
    """One ``tabular`` block, as rows of cleaned cells."""

    label: str
    spec: str
    rows: List[Row]
    header_rows: int
    line: int

    def cell(self, row: int, column: int) -> Optional[Cell]:
        if not 0 <= row < len(self.rows):
            return None
        return self.rows[row].at(column)

    def printed(self, row: int, column: int) -> Optional[str]:
        cell = self.cell(row, column)
        return None if cell is None else cell.text

    def find(self, needle: str, start: int = 0) -> int:
        """The index of the first row whose label contains ``needle``.

        Checks are written against the article's own row labels rather than against row
        numbers, so that inserting a row above does not silently shift every check.
        """
        for i in range(start, len(self.rows)):
            if _norm(needle) in _norm(self.rows[i].label()):
                return i
        raise ParseError(f"{self.label}: no row labelled {needle!r}")

    def find_all(self, needle: str) -> List[int]:
        return [i for i, row in enumerate(self.rows)
                if _norm(needle) in _norm(row.label())]

    def body(self) -> List[int]:
        """Row indices below the header, skipping full-width section headings."""
        width = max(row.width for row in self.rows)
        return [i for i in range(self.header_rows, len(self.rows))
                if not (len(self.rows[i].cells) == 1 and self.rows[i].cells[0].span >= width)]

    def column_label(self, column: int) -> str:
        parts: List[str] = []
        for i in range(self.header_rows):
            cell = self.rows[i].at(column)
            if cell is not None and cell.text and (cell.span > 1 or i == self.header_rows - 1):
                parts.append(cell.text)
        return " / ".join(parts) if parts else f"column {column}"


def _norm(text: str) -> str:
    """A label reduced to what identifies it.

    The arithmetic operators are kept. Without them the two perceptron rows of
    ``tab:grok-diagnostics``, ``n+m`` and ``n \\cdot m``, reduce to the same string and a
    check aimed at one silently reads the other.
    """
    return re.sub(r"[^a-z0-9+*^<>=]+", "", text.lower())


def read_tables(path: Optional[Path] = None) -> Dict[str, Table]:
    """Every labelled ``tabular`` in the article, by label.

    A block whose rows do not agree on a width is refused rather than guessed at: a
    mis-parsed row would put a computed value beside the wrong printed one, which is a
    worse failure than not checking the table at all.
    """
    source = (path or article_path()).read_text(encoding="utf-8")
    tables: Dict[str, Table] = {}
    label = ""
    lines = source.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        found = re.search(r"\\label\{(tab:[^}]+)\}", line)
        if found:
            label = found.group(1)
        if "\\begin{tabular}" in line:
            start = i
            depth = 0
            block: List[Tuple[int, str]] = []
            while i < len(lines):
                if "\\begin{tabular}" in lines[i]:
                    depth += 1
                if depth:
                    block.append((i + 1, lines[i]))
                if "\\end{tabular}" in lines[i]:
                    depth -= 1
                    if depth == 0:
                        break
                i += 1
            if label:
                tables[label] = _parse_block(label, block, start + 1)
            label = ""
        i += 1
    return tables


def _parse_block(label: str, block: Sequence[Tuple[int, str]], line: int) -> Table:
    spec = ""
    opening = re.search(r"\\begin\{tabular\}\s*(?:\[[^\]]*\])?\{([^}]*)\}", block[0][1])
    if opening:
        spec = opening.group(1)

    # Strip the delimiters, then rejoin physical lines: one logical row runs to its `\\`.
    body: List[Tuple[int, str]] = []
    for number, text in block:
        text = re.sub(r"\\begin\{tabular\}\s*(?:\[[^\]]*\])?\{[^}]*\}", "", text)
        text = text.replace("\\end{tabular}", "")
        text = re.sub(r"(?<!\\)%.*$", "", text)
        body.append((number, text))

    rows: List[Row] = []
    header_rows = 0
    seen_midrule = False
    buffer: List[str] = []
    buffer_line = body[0][0]
    for number, text in body:
        # The line a row is reported on is the line its *content* starts on. A `\midrule`
        # or an `\addlinespace` sitting alone above a row is buffered with it, and taking
        # the line the buffer opened on would point every such row at the rule above it.
        # Nothing downstream would notice: the row still parses, and only an edit made at
        # the reported line lands in the wrong row.
        if not any(_strip_rules(part).strip() for part in buffer):
            buffer_line = number
        while True:
            split = re.search(r"\\\\", text)
            if not split:
                buffer.append(text)
                break
            buffer.append(text[:split.start()])
            row = _parse_row("".join(buffer), buffer_line)
            if row is not None:
                rows.append(row)
                if not seen_midrule:
                    header_rows = len(rows)
            buffer = []
            text = text[split.end():]
            buffer_line = number
        if rows and not seen_midrule and re.search(r"\\midrule", text):
            seen_midrule = True
    tail = _parse_row("".join(buffer), buffer_line)
    if tail is not None:
        rows.append(tail)

    if not rows:
        raise ParseError(f"{label}: no rows")
    if not seen_midrule:
        header_rows = 1
    return Table(label=label, spec=spec, rows=rows, header_rows=header_rows, line=line)


def _parse_row(text: str, line: int) -> Optional[Row]:
    stripped = text.strip()
    if not stripped:
        return None
    stripped = _strip_rules(stripped)
    if not stripped.strip():
        return None

    cells: List[Cell] = []
    column = 0
    for raw in _split_ampersands(stripped):
        span, inner = _span_of(raw)
        cells.append(Cell(text=_clean(inner), raw=raw.strip(), column=column, span=span))
        column += span
    return Row(cells=cells, line=line)


def _split_ampersands(text: str) -> List[str]:
    parts: List[str] = []
    depth = 0
    current: List[str] = []
    i = 0
    while i < len(text):
        char = text[i]
        if char == "\\" and i + 1 < len(text):
            current.append(text[i:i + 2])
            i += 2
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
        if char == "&" and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(char)
        i += 1
    parts.append("".join(current))
    return parts


def _span_of(raw: str) -> Tuple[int, str]:
    found = re.search(r"\\multicolumn\s*\{(\d+)\}\s*\{[^}]*\}\s*", raw)
    if not found:
        return 1, raw
    rest = raw[found.end():]
    inner, after = _braced(rest)
    return int(found.group(1)), raw[:found.start()] + inner + after


def _braced(text: str) -> Tuple[str, str]:
    """Split ``{a}b`` into ``a`` and ``b``, respecting nesting."""
    text = text.lstrip()
    if not text.startswith("{"):
        return "", text
    depth = 0
    for i, char in enumerate(text):
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[1:i], text[i + 1:]
    return text[1:], ""


def _clean(raw: str) -> Optional[str]:
    text = raw
    for macro in _UNWRAP:
        while True:
            found = re.search(r"\\" + macro + r"\s*(\{\d+\}\s*\{[^}]*\}\s*)?", text)
            if not found:
                break
            inner, after = _braced(text[found.end():])
            text = text[:found.start()] + inner + after
    for old, new in _ESCAPES:
        text = text.replace(old, new)
    text = re.sub(r"\\phantom\s*\{[^}]*\}", "", text)
    for macro in _THIN:
        text = text.replace(macro, "")
    for macro in _SPACES:
        text = text.replace(macro, " ")
    text = text.replace("$", "")
    text = text.replace("{=}", "=").replace("\\times", "x").replace("\\cdot", "*")
    # A macro that survives this far keeps its name: `\tau` is the row label of tab:tau and
    # `\PR_{\mathrm{delay}}` names a row of tab:alts, so dropping the name would leave two
    # rows called the same nothing and no check could name the one it means.
    text = re.sub(r"\\([a-zA-Z]+)", r"\1", text)
    text = text.replace("{", "").replace("}", "")
    text = re.sub(r"\s+", " ", text).strip()
    if text in _MISSING or text == "":
        return None if text in _MISSING else ""
    return text


# ---------------------------------------------------------------- reading a printed cell

_NUMBER = re.compile(r"^[-+]?(\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?$")


def as_number(text: Optional[str]) -> Optional[float]:
    """The number a printed cell holds, or ``None`` if it does not hold one."""
    if text is None:
        return None
    body = text.strip().replace(",", "")
    if body.endswith("k") and _NUMBER.match(body[:-1] or "x"):
        return float(body[:-1]) * 1000.0
    if not _NUMBER.match(body):
        return None
    return float(body)


def decimals(text: str) -> int:
    """How many decimal places the article printed, which sets the comparison."""
    body = text.strip().replace(",", "")
    if body.endswith("k"):
        return 0
    if "." not in body:
        return 0
    return len(body.split(".")[1].rstrip())


def round_half_up(value: float, places: int) -> float:
    quantum = Decimal(1).scaleb(-places)
    return float(Decimal(repr(float(value))).quantize(quantum, rounding=ROUND_HALF_UP))


# ---------------------------------------------------------------- the report

OK = "ok"
ROUNDING = "rounding"
MISMATCH = "mismatch"
UNREADABLE = "unreadable"


CELL = "cell"
CLAIM = "claim"


@dataclass
class Finding:
    """One cell that was compared, or one claim that was settled, and how it came out."""

    label: str
    row: str
    column: str
    printed: Optional[str]
    computed: Optional[float]
    source: str
    status: str
    note: str = ""
    kind: str = CELL
    provenance: str = ""

    @property
    def bad(self) -> bool:
        return self.status in (ROUNDING, MISMATCH)

    def describe(self) -> str:
        if self.kind == CLAIM:
            return (f"{self.label:22s} {self.row[:26]:26s} claim                  "
                    f"article: {self.printed}\n"
                    f"{'':22s} {'':26s} {'':22s} files:   {self.computed}  {self.source}")
        printed = "---" if self.printed is None else self.printed
        if self.computed is None:
            got = "no value"
        elif isinstance(self.computed, str):
            got = self.computed
        else:
            got = f"{self.computed:.6f}".rstrip("0").rstrip(".")
        detail = f"  ({self.note})" if self.note else ""
        return (f"{self.label:22s} {self.row[:26]:26s} {self.column[:22]:22s} "
                f"printed {printed:>10s}  computed {got:>14s}  {self.source}{detail}")


@dataclass
class TableResult:
    label: str
    state: str                                    # "checked" or "skipped"
    reason: str = ""
    findings: List[Finding] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)

    @property
    def mismatches(self) -> List[Finding]:
        return [f for f in self.findings if f.bad]

    @property
    def checked(self) -> int:
        return len(self.findings)


@dataclass
class Report:
    results: List[TableResult]
    article: str = ""
    data: str = ""
    inputs: Dict[str, str] = field(default_factory=dict)

    @property
    def mismatches(self) -> List[Finding]:
        return [f for result in self.results for f in result.mismatches]

    @property
    def ok(self) -> bool:
        return not self.mismatches

    def by_label(self, label: str) -> TableResult:
        for result in self.results:
            if result.label == label:
                return result
        raise KeyError(label)

    @property
    def archived_inputs(self) -> List[str]:
        return sorted(name for name, source in self.inputs.items() if source == ARCHIVED)

    def rows(self) -> List[Dict[str, Any]]:
        """The report as a list of records, one per compared cell or settled claim.

        This is what ``check.tables`` writes as a CSV, so the fields are flat and ``status``
        is one of the four comparison constants, or ``"skipped"``. A skipped table
        contributes one row carrying its reason, so that the file says which tables were not
        checked as well as which cells disagreed: a checker that finds nothing to check and
        says nothing is wrong is the failure this whole module exists to prevent.
        """
        out: List[Dict[str, Any]] = []
        for result in self.results:
            if result.state == "skipped":
                out.append({"table": result.label, "kind": "table", "row": "",
                            "column": "", "printed": "", "computed": "", "source": "",
                            "provenance": "", "status": result.state, "note": result.reason})
                continue
            for finding in result.findings:
                out.append({
                    "table": finding.label,
                    "kind": finding.kind,
                    "row": finding.row,
                    "column": finding.column,
                    "printed": "" if finding.printed is None else finding.printed,
                    "computed": _as_text(finding.computed),
                    "source": finding.source,
                    "provenance": finding.provenance,
                    "status": finding.status,
                    "note": finding.note,
                })
        return out


def _provenance_of(source: str, read: Dict[str, str]) -> str:
    """How the files behind one finding got into ``data/``.

    A source string can name more than one file, so every recorded input the string mentions
    is looked up and the distinct answers are joined. ``archived`` in the result means the
    cell was checked against the numbers the article was written from rather than against a
    regeneration, which is weaker evidence and has to be visible as such.
    """
    found = [state for name, state in read.items() if name in source]
    if not found:
        return read.get(source, "")
    return " + ".join(sorted(set(found)))


def _as_text(value: Any) -> str:
    """A computed value at full precision, which is what the report has to show beside the
    printed one: rounding it here would hide exactly the disagreement being reported."""
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple)):
        return ", ".join(_as_text(v) for v in value)
    return repr(float(value))


# ---------------------------------------------------------------- the data side

ARCHIVED = "archived"
REGENERATED = "regenerated"
UNLISTED = "not in the manifest"
CODE = "code"


class Data:
    """The tracked half of the tree, read once per file, with its provenance kept.

    Every read is recorded against what ``data/manifest.json`` says produced the file. A
    table checked against an archived file has been checked against the numbers the article
    was written from, not against a regeneration, and the report has to say which, or the
    check reads as stronger evidence than it is.
    """

    def __init__(self, root: Optional[Path] = None):
        self.root = root or data_root()
        self._frames: Dict[str, pd.DataFrame] = {}
        self._objects: Dict[str, Any] = {}
        self._manifest = load_manifest().get("files", {}) if self.root == data_root() else {}
        self.read: Dict[str, str] = {}

    def has(self, rel: str) -> bool:
        return (self.root / rel).exists()

    def require(self, rel: str) -> Path:
        path = self.root / rel
        if not path.exists():
            raise FileNotFoundError(f"data/{rel} is missing; run `actdim bootstrap` first")
        entry = self._manifest.get(rel, {})
        self.read[self.name(rel)] = (ARCHIVED if entry.get("source") == ARCHIVED
                                     else REGENERATED if entry else UNLISTED)
        return path

    def frame(self, rel: str) -> pd.DataFrame:
        if rel not in self._frames:
            self._frames[rel] = pd.read_csv(self.require(rel))
        else:
            self.require(rel)
        return self._frames[rel]

    def json(self, rel: str) -> Any:
        if rel not in self._objects:
            self._objects[rel] = json.loads(self.require(rel).read_text(encoding="utf-8"))
        else:
            self.require(rel)
        return self._objects[rel]

    def note_code(self, name: str) -> str:
        """Record a source that is a module of this package rather than a file in ``data/``.

        The run registry of appendix O is the only such source. It is code, so it is neither
        archived nor regenerated, and it is what the article's budget column is checked
        against because no committed file records the perceptron budgets.
        """
        self.read[name] = CODE
        return name

    @staticmethod
    def name(rel: str) -> str:
        return "data/" + rel


@dataclass
class Computed:
    """One recomputed cell, ready to be diffed against what the article prints.

    ``tolerance`` widens the comparison for a cell whose printed form is not a rounding of
    the computed one. The only use is a step index that falls between two logged steps: the
    S_5 runs log every five steps, so a window centre lands on 712.5 and the article prints
    712. Everything else compares at the precision printed and nothing else.
    """

    row: int
    column: int
    value: Any                                    # float, str, None, or a list of those
    source: str
    note: str = ""
    tolerance: float = 0.0
    column_name: str = ""
    """What to call the column in the report, where the header does not say.

    ``tab:ceiling`` is two scans stacked in one ``tabular``, so the second block's columns
    are headed by a row inside the body and the header above says ``E_max``. Left to the
    header, a disagreement in the record scan would be reported against an embedding
    dimension it has nothing to do with.
    """


@dataclass
class Claim:
    """A statement a caption or the surrounding text makes, which ``data/`` can settle.

    Three of the defects already on record are of this shape rather than the shape of a
    wrong cell: ``tab:alts``'s two columns are aggregated differently and the caption does
    not say so, ``tab:ladder``'s caption describes a sliding-window median for rows that
    have one window, and the text under ``tab:runs`` names the wrong four runs as the
    sketched ones. A checker that only compared cells would pass all three, so claims are
    checked here beside the cells and count the same way towards the exit status.
    """

    row: str                                      # what to call it in the report
    statement: str                                # what the article says
    holds: bool
    finding: str                                  # what the files say instead
    source: str


Check = Callable[[Table, Data], Iterable[Any]]    # yields Computed or Claim


# ---------------------------------------------------------------- shared conventions

# ``tab:alts``, ``tab:obs`` and the observer figure all drop these two, for the reasons
# appendix D gives: probe accuracy is quantised and degenerate in every window, and the
# instantaneous mini-batch loss fails requirement 4, still reading 0.91-6.93 at zero
# learning rate.
DROPPED_OBSERVERS = ("acc_probe", "loss_step")

# The four ranks withheld from the eight-direction calibration.
HELD_OUT_EIGHT = (1, 3, 5, 8)

# The ten ranks ``tab:k20`` prints. NOT the ranks ``tab:alts`` scores; see the docstring.
K20_PRINTED = (1, 2, 4, 6, 8, 10, 12, 14, 17, 20)

ALTS_STATISTICS = ("MG", "LB", "TwoNN", "PRdelay", "specPR256", "specPR1024", "specPR0",
                   "roughness")


def _spearman(a: np.ndarray, b: np.ndarray) -> Optional[float]:
    """Spearman correlation, or ``None`` where it is not defined.

    scipy raises a ConstantInputWarning -- a RuntimeWarning, which pytest turns into an
    error here -- on a constant input, and returns NaN. Both cases are refusals, so they
    are caught before the call rather than after.
    """
    from scipy.stats import spearmanr

    ok = np.isfinite(a) & np.isfinite(b)
    if ok.sum() < 3:
        return None
    x, y = a[ok], b[ok]
    if np.all(x == x[0]) or np.all(y == y[0]):
        return None
    return float(spearmanr(x, y).statistic)


def _mae(a: np.ndarray, b: np.ndarray) -> Optional[float]:
    ok = np.isfinite(a) & np.isfinite(b)
    if not ok.any():
        return None
    return float(np.mean(np.abs(a[ok] - b[ok])))


def _slope(x: np.ndarray, y: np.ndarray) -> Optional[float]:
    """Least-squares slope of ``y`` on ``x``, without numpy's fitting warnings."""
    ok = np.isfinite(x) & np.isfinite(y)
    if ok.sum() < 2:
        return None
    x, y = x[ok], y[ok]
    var = float(np.sum((x - x.mean()) ** 2))
    if var == 0.0:
        return None
    return float(np.sum((x - x.mean()) * (y - y.mean())) / var)


def _median_or_none(values: Sequence[float]) -> Optional[float]:
    finite = [v for v in values if v is not None and np.isfinite(v)]
    if not finite:
        return None
    return float(np.median(finite))


def _nan_to_none(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return None if math.isnan(number) else number


# ---------------------------------------------------------------- the checks

def check_frozen(table: Table, data: Data) -> Iterable[Computed]:
    eight = data.json("calib.e8/frozen_config.json")
    twenty = data.json("calib.e20/frozen_k20.json")
    ranking = data.frame("calib.e8/config_ranking.csv")
    sweep = data.frame("sys.digits.parameter/sweep_raw.csv")

    e8, e20 = "calib.e8/frozen_config.json", "calib.e20/frozen_k20.json"
    rank_file = "calib.e8/config_ranking.csv"
    yield Computed(table.find("E_{max}"), 1, float(eight["config"]["max_E"]), Data.name(e8))
    yield Computed(table.find("E_{max}"), 2, float(twenty["config"]["max_E"]), Data.name(e20))
    yield Computed(table.find("tau"), 1, float(eight["config"]["tau"]), Data.name(e8))
    yield Computed(table.find("tau"), 2, float(twenty["config"]["tau"]), Data.name(e20))
    window = table.find("window / stride")
    yield Computed(window, 1, [float(eight["config"]["window"]), float(eight["config"]["stride"])],
                   Data.name(e8))
    yield Computed(window, 2, [float(twenty["config"]["window"]), float(twenty["config"]["stride"])],
                   Data.name(e20))
    yield Computed(table.find("grid size"), 1, float(len(ranking)), Data.name(rank_file))
    yield Computed(table.find("selection seeds"), 1,
                   [float(s) for s in eight["cal_seeds"]], Data.name(e8))
    yield Computed(table.find("selection seeds"), 2,
                   [float(s) for s in twenty["calibration_seeds"]], Data.name(e20))
    yield Computed(table.find("selection ranks"), 1,
                   [float(r) for r in eight["cal_r"]], Data.name(e8))
    yield Computed(table.find("selection ranks"), 2,
                   [float(r) for r in twenty["calibration_r"]], Data.name(e20))

    withheld = sorted(set(sweep.r.unique()) - set(eight["cal_r"]))
    yield Computed(table.find("withheld ranks"), 1, [float(r) for r in withheld],
                   Data.name("sys.digits.parameter/sweep_raw.csv"),
                   "the sweep's ranks less the calibration ranks")

    yield Computed(table.find("selection error, best"), 1, float(ranking.mae.min()),
                   Data.name(rank_file))
    yield Computed(table.find("selection error, worst"), 1, float(ranking.mae.max()),
                   Data.name(rank_file))


def check_geometry(table: Table, data: Data) -> Iterable[Computed]:
    config = data.json("calib.e8/frozen_config.json")["config"]
    row = table.find("frozen configuration")
    yield Computed(row, 1, float(config["window"]), Data.name("calib.e8/frozen_config.json"))
    yield Computed(row, 2, float(config["stride"]), Data.name("calib.e8/frozen_config.json"))


def _digits_parameter_eight(data: Data) -> Tuple[pd.DataFrame, str]:
    """The parameter-subspace sweep, on the recurrent arm, at the withheld ranks."""
    rel = "sys.digits.parameter/sweep_raw.csv"
    frame = data.frame(rel)
    frame = frame[(frame.arm == "qp") & (~frame.eta_zero)
                  & (~frame.observer.isin(DROPPED_OBSERVERS))
                  & frame.r.isin(HELD_OUT_EIGHT)]
    return frame, Data.name(rel)


def _alts_eight(data: Data) -> Tuple[Dict[str, Tuple[Optional[float], Optional[float]]], str]:
    """``tab:alts`` columns 1-2. One value per rank: the median over seeds and observers.

    Keeping all twelve observers instead gives MG 0.455 and TwoNN 1.752, so the two
    exclusions of ``DROPPED_OBSERVERS`` are load-bearing rather than cosmetic.
    """
    frame, source = _digits_parameter_eight(data)
    grouped = frame.groupby("r")
    truth = grouped.traj_PR.median().values
    out = {}
    for statistic in ALTS_STATISTICS:
        series = grouped[statistic].median().values
        out[statistic] = (_mae(series, truth), _spearman(series, truth))
    return out, source


def _alts_twenty(data: Data, ranks: Optional[Sequence[int]] = None
                 ) -> Tuple[Dict[str, Tuple[Optional[float], Optional[float]]], str]:
    """``tab:alts`` columns 3-4. All twenty ranks of the k20 calibration by default.

    Note the asymmetry with the eight-direction column: there is no held-out restriction
    here, so five of the twenty ranks -- 2, 6, 10, 14, 18 -- are the ranks the configuration
    was itself selected on. That is what reproduces the printed numbers.

    Passing ``ranks`` restricts the scoring, which is how the size of the asymmetry is
    produced as a number rather than asserted in a comment.
    """
    rel = "calib.e20/scores_frozen.csv"
    frame = data.frame(rel)
    frame = frame[frame.tag == "qp"]
    if ranks is not None:
        frame = frame[frame.r.isin(list(ranks))]
    grouped = frame.groupby("r")
    truth = grouped.traj_pr.median().values
    out = {}
    for statistic in ALTS_STATISTICS:
        series = grouped[statistic].median().values
        out[statistic] = (_mae(series, truth), _spearman(series, truth))
    return out, Data.name(rel)


_ALTS_ROWS = (("MG", "MG"), ("LB", "LB"), ("TwoNN", "TwoNN"), ("PR_{delay}", "PRdelay"),
              ("256 bands", "specPR256"), ("1024 bands", "specPR1024"),
              ("native resolution", "specPR0"), ("roughness", "roughness"))


def check_alts(table: Table, data: Data) -> Iterable[Any]:
    eight, source8 = _alts_eight(data)
    twenty, source20 = _alts_twenty(data)
    for label, statistic in _ALTS_ROWS:
        row = table.find(label)
        yield Computed(row, 1, eight[statistic][0], source8)
        yield Computed(row, 2, eight[statistic][1], source8)
        yield Computed(row, 3, twenty[statistic][0], source20)
        yield Computed(row, 4, twenty[statistic][1], source20)

    # Errata item 3. The printed cells reproduce, so nothing above catches this: what is
    # wrong is that the two halves of the table were aggregated by different rules and the
    # caption presents them as one measurement at two ranges.
    held, _ = _alts_twenty(data, ranks=K20_PRINTED)
    printed = table.printed(table.find("MG"), 3)
    detail = ", ".join(f"{name} {held[name][0]:.3f}" for name in ALTS_STATISTICS[:4]
                       if held[name][0] is not None)
    caption = _caption_of(table)
    qualified = "all twenty" in caption and "withheld" in caption
    yield Claim(
        row="aggregation of the two halves",
        statement=("the caption says which ranks each half scores" if qualified else
                   "both halves score the withheld ranks, which is the convention the "
                   "appendix D preamble states and the caption does not qualify"),
        holds=qualified,
        finding=(f"the eight-direction half scores the four withheld ranks "
                 f"{list(HELD_OUT_EIGHT)}; the twenty-direction half scores all twenty, "
                 f"the five selection ranks 2, 6, 10, 14, 18 included. Restricted to the "
                 f"ten ranks tab:k20 prints it gives {detail}, against a printed MG of "
                 f"{printed}"),
        source=source20)


def _caption_of(table: Table) -> str:
    """The caption of the float a table sits in, as plain text.

    Several defects on record are captions that describe a different aggregation from the
    one the columns were computed by, so the caption has to be readable from here.
    """
    source = article_path().read_text(encoding="utf-8").split("\n")
    start = next((i for i in range(table.line, 0, -1)
                  if "\\begin{table}" in source[i - 1]), None)
    if start is None:
        return ""
    block = "\n".join(source[start - 1:table.line])
    found = re.search(r"\\caption\{", block)
    return _clean(_braced(block[found.end() - 1:])[0]) or "" if found else ""


def check_k20(table: Table, data: Data) -> Iterable[Computed]:
    rel = "calib.e20/scores_frozen.csv"
    frame = data.frame(rel)
    frame = frame[(frame.tag == "qp") & frame.r.isin(K20_PRINTED)]
    grouped = frame.groupby("r")
    spread = (frame.groupby(["observer", "r"]).MG.agg(lambda s: s.max() - s.min())
              .groupby("r").median())
    series = {
        "MG": grouped.MG.median(),
        "PR_{delay}": grouped.PRdelay.median(),
        "spectral PR": grouped.specPR256.median(),
        "spread across seeds": spread,
    }
    for label, values in series.items():
        row = table.find(label)
        for column, rank in enumerate(K20_PRINTED, start=1):
            yield Computed(row, column, float(values.loc[rank]), Data.name(rel))


_LADDER_RANKING = (
    ("online linear regression", "sys.linear"),
    ("logistic regression", "sys.logistic"),
    ("frozen nonlinear decoder", "sys.decoder"),
    ("perceptron in a k-subspace", "sys.subspace"),
)


def _ladder_best(data: Data, experiment: str) -> Tuple[float, float, str]:
    """The best observer's error and rank correlation, recomputed from the per-cell file.

    ``observer_ranking.csv`` already holds this, but it is the file the article quotes, so
    reading it alone would check the table against itself. The value is recomputed here from
    ``heldout_raw.csv``, which is one row per (rank, seed, observer): the estimate at a rank
    is the median over the withheld seeds, the error is the mean over the withheld ranks of
    the distance from the constructed truth, and the correlation is over the ranks. The
    ranking file is read as well, so that a disagreement between the two committed files is
    reported rather than inherited.
    """
    raw_rel = experiment + "/heldout_raw.csv"
    ranking_rel = experiment + "/observer_ranking.csv"
    raw = data.frame(raw_rel)
    scores: Dict[str, Tuple[float, Optional[float]]] = {}
    for observer, group in raw.groupby("observer"):
        cell = group.groupby("k", sort=True).agg(truth=("truth", "first"),
                                                 estimate=("MG", "median"))
        scores[str(observer)] = (float((cell.estimate - cell.truth).abs().mean()),
                                 _spearman(cell.truth.values, cell.estimate.values))
    name = min(scores, key=lambda o: scores[o][0])
    mae, rho = scores[name]
    ranked = data.frame(ranking_rel).iloc[0]
    source = f"{Data.name(raw_rel)} + {Data.name(ranking_rel)}"
    if str(ranked.observer) != name:
        source += f" (disagree: ranking names {ranked.observer}, the cells name {name})"
    return mae, rho, source


def check_ladder(table: Table, data: Data) -> Iterable[Any]:
    rel = "sys.matrix/stationary_validation.csv"
    matrix = data.frame(rel)
    held = matrix[matrix.split == "held_out"].groupby("seed")[["mae", "rho"]].first()
    row = table.find("oscillating matrix")
    yield Computed(row, 3, [float(v) for v in held.mae.values], Data.name(rel))
    yield Computed(row, 4, [float(v) for v in held.rho.values], Data.name(rel),
                   "seeds in the same order as the errors beside them")

    for label, experiment in _LADDER_RANKING:
        mae, rho, source = _ladder_best(data, experiment)
        row = table.find(label)
        yield Computed(row, 3, mae, source)
        yield Computed(row, 4, rho, source)

    frame, source = _digits_parameter_eight(data)
    row = table.find_all("image data, parameter subspace")[0]
    yield Computed(row, 3, _mae(frame.MG.values, frame.traj_PR.values), source,
                   "mean over the withheld (rank, seed, observer) runs")
    grouped = frame.groupby("r")
    yield Computed(row, 4, _spearman(grouped.MG.median().values,
                                    grouped.traj_PR.median().values), source)

    twenty, source20 = _alts_twenty(data)
    row = table.find_all("image data, parameter subspace")[1]
    yield Computed(row, 3, twenty["MG"][0], source20)
    yield Computed(row, 4, twenty["MG"][1], source20)

    mae, rho, source = _ladder_best(data, "sys.digits.function")
    row = table.find("image data, function subspace")
    yield Computed(row, 3, mae, source)
    yield Computed(row, 4, rho, source)

    # Errata item 9. The caption says each side of the error is a median over that run's
    # sliding windows. The archived files held one estimate per (rank, seed, observer) and
    # no window index, so the claim was false of every constructed row; the regenerated
    # ones record how many windows each estimate collapses, so it can be settled directly.
    windows = {}
    for _, experiment in _LADDER_RANKING:
        raw = data.frame(experiment + "/heldout_raw.csv")
        windows[experiment] = sorted(int(v) for v in raw.n_windows.unique())
    single = [e for e, counts in windows.items() if max(counts) == 1]
    yield Claim(
        row="one window or several",
        statement="each side of the error is a median over that run's sliding windows",
        holds=not single,
        finding=("every constructed row slides: " + ", ".join(
            f"{Data.name(e + '/heldout_raw.csv')} {counts}" for e, counts in windows.items())
            if not single else
            f"{len(single)} row(s) have one window per run: {', '.join(single)}"),
        source=", ".join(Data.name(e + "/heldout_raw.csv") for e in windows))

    # Requirement 1: a rank whose excitation was not confirmed is not a constructed truth,
    # and a row that scores one is not reporting recovery.
    for label, experiment in _LADDER_RANKING + (("image data, function subspace",
                                                 "sys.digits.function"),):
        raw = data.frame(experiment + "/heldout_raw.csv")
        unverified = sorted(set(raw.loc[~raw.verified.astype(bool), "k"]))
        if unverified:
            yield Claim(
                row=label,
                statement="every rank in the row is a verified construction",
                holds=False,
                finding=(f"rank(s) {', '.join(str(int(k)) for k in unverified)} did not "
                         f"pass the excitation check"),
                source=Data.name(experiment + "/heldout_raw.csv"))


# Article name -> the observer identifiers in the committed sweep.
_OBSERVERS = (
    ("probe loss", ("loss_probe",)),
    ("function-space norm", ("fn_fro",)),
    ("margin", ("margin",)),
    ("parameter norms (two)", ("c_norm", "w_fro")),
    ("fixed parameter projection", ("c_proj1",)),
    ("gradient projection", ("g_proj",)),
    ("function-space projection", ("fn_proj1",)),
    ("gradient norm", ("g_fro",)),
    ("full-batch loss", ("loss_full",)),
    ("instantaneous loss", ("loss_step",)),
)


def _observer_scores(data: Data) -> Tuple[Dict[str, Tuple[Optional[float], ...]], str]:
    """Per observer: error, slope and whether roughness orders the four withheld ranks.

    This is the caption's recipe -- median over the four withheld seeds at each of the four
    withheld ranks, scored against the measured effective rank -- and not the raw mean over
    runs, which gives 0.49 for the probe loss where the article prints 0.30.
    """
    rel = "sys.digits.parameter/sweep_raw.csv"
    frame = data.frame(rel)
    frame = frame[(frame.arm == "qp") & (~frame.eta_zero) & frame.r.isin(HELD_OUT_EIGHT)]
    out: Dict[str, Tuple[Optional[float], ...]] = {}
    for observer, part in frame.groupby("observer"):
        grouped = part.groupby("r")
        estimate = grouped.MG.median().values
        truth = grouped.traj_PR.median().values
        roughness = grouped.roughness.median().values
        out[str(observer)] = (_mae(estimate, truth), _slope(truth, estimate),
                              _spearman(roughness, truth))
    return out, Data.name(rel)


def check_obs(table: Table, data: Data) -> Iterable[Computed]:
    scores, source = _observer_scores(data)
    for label, observers in _OBSERVERS:
        row = table.find(label)
        mae = _median_or_none([scores[o][0] for o in observers if o in scores])
        slope = _median_or_none([scores[o][1] for o in observers if o in scores])
        orders = [scores[o][2] for o in observers if o in scores]
        yield Computed(row, 2, mae, source)
        yield Computed(row, 3, slope, source)
        ordered = all(v is not None and v >= 1.0 for v in orders) if orders else None
        yield Computed(row, 4, None if ordered is None else ("yes" if ordered else "no"),
                       source, "roughness orders the four ranks exactly")


def check_aggregation(table: Table, data: Data) -> Iterable[Computed]:
    frame, source = _digits_parameter_eight(data)
    yield Computed(table.find("mean over"), 2,
                   _mae(frame.MG.values, frame.traj_PR.values), source)
    scores, source_obs = _observer_scores(data)
    per_observer = [value[0] for observer, value in scores.items()
                    if observer not in DROPPED_OBSERVERS]
    yield Computed(table.find("median over observers"), 2,
                   _median_or_none(per_observer), source_obs)
    eight, source8 = _alts_eight(data)
    yield Computed(table.find("median over seeds and observers"), 2, eight["MG"][0], source8)


def check_tau(table: Table, data: Data) -> Iterable[Computed]:
    rel = "valid.tau/tau_sensitivity.csv"
    frame = data.frame(rel)
    frame = frame[(frame.period == 400) & (frame.max_E == 20)]
    ranks = [1, 2, 3, 4, 6, 8]
    for row in table.body():
        lag = as_number(table.printed(row, 0))
        if lag is None:
            continue
        part = frame[frame.tau == str(int(lag))]
        if part.empty:
            continue
        spans = part.span_periods.unique()
        if len(spans) == 1:
            yield Computed(row, 1, float(spans[0]), Data.name(rel))
        medians = part.groupby("r").MG.median()
        for column, rank in enumerate(ranks, start=2):
            if rank in medians.index:
                yield Computed(row, column, float(medians.loc[rank]), Data.name(rel))


# Article name -> the control identifier in the nuisance sweep.
_CONTROLS = (
    ("none (baseline)", "baseline"),
    ("learning rate halved", "lr_step"),
    ("drive band up one octave", "freq_double"),
    ("drive band down one octave", "freq_half"),
    ("coordinates rotated", "rotate"),
    ("observer gain ramped", "obs_scale"),
    ("state amplitude ramped", "amp_ramp"),
)

# The denominator of the percentage column: a real change of four components.
FOUR_COMPONENTS = 4.0


def check_controls(table: Table, data: Data) -> Iterable[Any]:
    rel = "valid.nuisance/controls_scored.csv"
    frame = data.frame(rel)
    frame = frame[frame["mode"] == "qp"]
    for label, control in _CONTROLS:
        part = frame[frame.control == control]
        if part.empty:
            continue
        shift = float(part["between"].median())
        row = table.find(label)
        yield Computed(row, 1, shift, Data.name(rel))
        yield Computed(row, 2, 100.0 * shift / FOUR_COMPONENTS, Data.name(rel),
                       "as a percentage of a four-component change")

    # The caption's two omissions, against the twenty-direction invariance file. This is
    # what settles errata item 24: the archived README still lists the constant rescaling
    # as needing a fix at source, and the committed file has read 0.000 throughout since
    # before the port began.
    rel = "calib.e20/invariance_controls.csv"
    controls = data.frame(rel)
    rescale = controls[controls.control == "qp_scale2"].delta_MG.abs()
    rotate = controls[controls.control == "qp_rotate"].delta_MG.abs()
    yield Claim(
        row="constant rescaling",
        statement="a constant rescaling of the observer moves the estimate by 0.000",
        holds=bool(round_half_up(float(rescale.max()), 3) == 0.0),
        finding=(f"largest shift over {len(rescale)} observers is "
                 f"{float(rescale.max()):.3g}"),
        source=Data.name(rel))
    invariant = int((rotate.round(3) == 0.0).sum())
    yield Claim(
        row="rotation of the coordinates",
        statement=("the observers other than the fixed parameter projection are invariant "
                   "to a rotation by construction"),
        holds=invariant == len(rotate) - 1,
        finding=(f"{invariant} of {len(rotate)} observers read 0.000 under rotation; the "
                 f"exception moves by {float(rotate.max()):.3f}"),
        source=Data.name(rel))


def check_switch(table: Table, data: Data) -> Iterable[Computed]:
    rel = "valid.transitions/transitions_raw.csv"
    frame = data.frame(rel)
    frame = frame[(frame["mode"] == "qp") & frame.observer.isin(("w_fro", "c_norm"))]
    for row in table.body():
        label = table.printed(row, 0) or ""
        levels = re.findall(r"\d+", label)
        if len(levels) < 2:
            continue
        high, low = int(levels[0]), int(levels[1])
        part = frame[(frame.hi == high) & (frame.lo == low)]
        if part.empty:
            continue
        for column, field_name in enumerate(("level0", "level1", "level2"), start=1):
            yield Computed(row, column, float(part[field_name].median()), Data.name(rel),
                           "median over seeds and the two parameter norms")


def check_aniso(table: Table, data: Data) -> Iterable[Computed]:
    rel = "valid.anisotropy/aniso_summary.csv"
    frame = data.frame(rel)
    for row in table.body():
        rank = as_number(table.printed(row, 0))
        anisotropy = as_number(table.printed(row, 1))
        if rank is None or anisotropy is None:
            continue
        part = frame[(frame.r == int(rank)) & (np.abs(frame.rho - anisotropy) < 1e-9)]
        if part.empty:
            continue
        record = part.iloc[0]
        yield Computed(row, 2, float(record.pr_pos), Data.name(rel))
        yield Computed(row, 3, float(record.MG), Data.name(rel))
        yield Computed(row, 4, float(record.PRdelay), Data.name(rel))


_GROUND_TRUTH_ARMS = (("qp, eta=0", "qp_eta0"),)


def check_gt(table: Table, data: Data) -> Iterable[Computed]:
    rel = "sys.digits.parameter/ground_truth_PR.csv"
    frame = data.frame(rel).set_index("arm")
    ranks = ("1", "2", "4", "6", "8")
    for row in table.body():
        label = (table.printed(row, 0) or "").strip()
        arm = dict(_GROUND_TRUTH_ARMS).get(label.replace("$", ""), label)
        if arm not in frame.index:
            continue
        for column, rank in enumerate(ranks, start=1):
            yield Computed(row, column, float(frame.loc[arm, rank]), Data.name(rel))


# Article row -> (file, run, column). The transformer rows read the parameter norm and the
# perceptron rows the training loss, which is what the caption says.
_DIAGNOSTIC_ROWS = (
    ("transformer, full data", "grok.diagnostics.logs/real_logs_summary.csv",
     "grokpos_s0", "weight_norm"),
    ("transformer, reduced data, s0", "grok.diagnostics.logs/real_logs_summary.csv",
     "lowdata15_s0", "weight_norm"),
    ("transformer, reduced data, s2", "grok.diagnostics.logs/real_logs_summary.csv",
     "lowdata15_s2", "weight_norm"),
    ("transformer, no weight decay", "grok.diagnostics.logs/real_logs_summary.csv",
     "wd0_s0", "weight_norm"),
    ("perceptron, n+m", "grok.diagnostics.perceptron/dimension_probe_summary.csv",
     "a_add", "train_loss"),
    ("perceptron, n \\cdot m", "grok.diagnostics.perceptron/dimension_probe_summary.csv",
     "a_mul", "train_loss"),
    ("perceptron, n^3+nm^2+m", "grok.diagnostics.perceptron/dimension_probe_summary.csv",
     "x_no_grok", "train_loss"),
)

_DIAGNOSTIC_COLUMNS = ((2, "MG"), (3, "ident"), (4, "roughness"), (5, "PRdelay"), (6, "osc"))


def check_grok_diagnostics(table: Table, data: Data) -> Iterable[Computed]:
    outcomes = data.frame("grok.extended.outcomes/exp8_outcomes.csv").set_index("run")
    for label, rel, run, column in _DIAGNOSTIC_ROWS:
        frame = data.frame(rel)
        part = frame[(frame.run == run) & (frame.column == column)]
        if part.empty:
            continue
        record = part.iloc[0]
        row = table.find(_row_needle(label))
        if run in outcomes.index:
            yield Computed(row, 1, "yes" if bool(outcomes.loc[run, "groks"]) else "no",
                           Data.name("grok.extended.outcomes/exp8_outcomes.csv"))
        for position, name in _DIAGNOSTIC_COLUMNS:
            yield Computed(row, position, float(record[name]), Data.name(rel))


def _row_needle(label: str) -> str:
    """The part of a row label that survives cleaning, for ``Table.find``."""
    return _clean(label) or label


_DIP_STATS = (("function", "fn_PR_pos_det"), ("parameter", "PR_pos_det"))
_DIP_RUNS = ("mod_wd1", "mod_wd1_s43", "mod_wd1_s44", "s5_wd1", "mod_wd0", "s5_wd0")

# The two runs whose window centres fall on half-steps. They log every five optimiser steps
# and a window centre is the mean of two logged steps, so an offset from generalisation can
# land on 712.5, which the article prints as 712. Half a logged step is the whole of the
# allowance; anything larger would let a genuinely different window pass as this one.
HALF_STEP_RUNS = ("s5_wd1", "s5_wd0")
HALF_STEP = 0.5


def check_dip(table: Table, data: Data) -> Iterable[Computed]:
    dip = data.frame("grok.rank.dip/rank_dip.csv")
    controls = data.frame("grok.rank.dip/rank_dip_controls_aligned.csv")
    windows = data.frame("grok.rank.dip/rank_windows.csv")
    dip_file = Data.name("grok.rank.dip/rank_dip.csv")
    control_file = Data.name("grok.rank.dip/rank_dip_controls_aligned.csv")
    window_file = Data.name("grok.rank.dip/rank_windows.csv")

    block = 0
    for row in table.body():
        space = table.printed(row, 0)
        if space:
            block = 0 if _norm(space) == "function" else 1
        run = table.printed(row, 1)
        if run not in _DIP_RUNS:
            continue
        statistic = _DIP_STATS[block][1]
        slack = HALF_STEP if run in HALF_STEP_RUNS else 0.0
        source = dip[(dip.run == run) & (dip.stat == statistic)]
        if not source.empty:
            record = source.iloc[0]
            yield Computed(row, 2, float(record.plateau), dip_file)
            yield Computed(row, 3, float(record.dip), dip_file)
            yield Computed(row, 4, float(record.depth), dip_file)
            yield Computed(row, 5, float(record["at"]), dip_file, "steps after generalisation",
                           tolerance=slack)
            trace = windows[windows.run == run]
            generalised = trace.t_gen.dropna()
            if not generalised.empty:
                floor = float(generalised.iloc[0]) + float(record["at"])
                after = trace[trace.right_step > floor][statistic]
                if not after.empty:
                    yield Computed(row, 6, float(after.max()), window_file,
                                   "largest value at any window after the dip")
            continue
        source = controls[(controls.run == run) & (controls.stat == statistic)]
        if not source.empty:
            record = source.iloc[0]
            yield Computed(row, 2, float(record.plateau), control_file)
            yield Computed(row, 3, float(record.dip), control_file)
            yield Computed(row, 4, float(record.depth), control_file)
            yield Computed(row, 5, None, control_file, "measured in the aligned window")
            yield Computed(row, 6, None, control_file, "measured in the aligned window")


def check_prwindow(table: Table, data: Data) -> Iterable[Computed]:
    rel = "grok.prwindow/pr_vs_window.csv"
    frame = data.frame(rel)
    frame = frame[frame.ladder == "fixed_n"]
    columns = (("a_add", 1, "PR_pos_det_med"), ("a_add", 2, "PR_pos_det_max"),
               ("x_no_grok", 3, "PR_pos_det_med"), ("x_no_grok", 4, "PR_pos_det_max"))
    for row in table.body():
        window = as_number(table.printed(row, 0))
        if window is None:
            continue
        for run, column, name in columns:
            part = frame[(frame.run == run) & (frame.window_steps == int(window))]
            if part.empty:
                continue
            yield Computed(row, column, float(part.iloc[0][name]), Data.name(rel))


# Article row -> (run, the run its window is aligned on).
_MATCHED_RUNS = (
    ("modular, seed 42", "mod_wd1", "mod_wd1"),
    ("modular, seed 43", "mod_wd1_s43", "mod_wd1_s43"),
    ("modular, seed 44", "mod_wd1_s44", "mod_wd1_s44"),
    ("S_5 composition", "s5_wd1", "s5_wd1"),
    ("modular, no decay", "mod_wd0", "mod_wd1"),
    ("S_5, no decay", "s5_wd0", "s5_wd1"),
)

# The caption's window: the plateau is the median over [t-3000, t-1000] and the floor the
# minimum over [t-1000, t+2000].
MATCHED_BEFORE, MATCHED_AFTER = 1000.0, 2000.0


def check_matched(table: Table, data: Data) -> Iterable[Computed]:
    spread = data.frame("grok.matched.surrogate/surrogate_seed_spread.csv")
    trace = data.frame("grok.matched.window/headline_trace.csv")
    spread_file = Data.name("grok.matched.surrogate/surrogate_seed_spread.csv")
    trace_file = Data.name("grok.matched.window/headline_trace.csv")

    generalisation = {}
    for _, run, _ in _MATCHED_RUNS:
        steps = trace[trace.run == run].t_gen.dropna()
        if not steps.empty:
            generalisation[run] = float(steps.iloc[0])

    for label, run, aligned_on in _MATCHED_RUNS:
        row = table.find(_row_needle(label))
        part = spread[(spread.run == run) & (spread.column == "weight_norm")]
        if part.empty:
            continue
        yield Computed(row, 1, float(part.iloc[0].observed), spread_file)
        step = generalisation.get(aligned_on)
        if step is not None:
            window = trace[(trace.run == run) & (trace.column == "weight_norm")
                           & (trace.mid_step >= step - MATCHED_BEFORE)
                           & (trace.mid_step <= step + MATCHED_AFTER)]
            if not window.empty:
                floor = float(window.loc[window.MG.idxmin(), "mid_step"]) - step
                yield Computed(row, 3, floor, trace_file,
                               "offset of the minimum from generalisation",
                               tolerance=HALF_STEP if run in HALF_STEP_RUNS else 0.0)
        for column, smooth in ((4, 101), (5, 201), (6, 401)):
            at_smooth = part[part.smooth == smooth]
            if not at_smooth.empty:
                yield Computed(row, column, float(at_smooth.iloc[0].p_median), spread_file)


def check_theiler(table: Table, data: Data) -> Iterable[Any]:
    rel = "valid.theiler.cap/theiler_quick_raw.csv"
    frame = data.frame(rel)
    # Median over seeds per observer, then over the three observers: pooling the raw rows
    # instead mixes seed spread into the observer median and moves r = 5 from 4.53 to 6.99.
    collapsed = (frame.groupby(["theiler", "r", "observer"])[["MG", "truth"]].median()
                 .groupby(level=[0, 1]).median())
    exclusions = sorted(frame.theiler.unique())
    ranks, estimates = [], {e: [] for e in exclusions}
    truths = []
    for row in table.body():
        rank = as_number(table.printed(row, 0))
        if rank is None:
            continue
        rank = int(rank)
        if (exclusions[0], rank) not in collapsed.index:
            continue
        ranks.append(rank)
        truth = float(collapsed.loc[(exclusions[0], rank), "truth"])
        truths.append(truth)
        yield Computed(row, 1, truth, Data.name(rel))
        for column, exclusion in enumerate(exclusions, start=2):
            value = float(collapsed.loc[(exclusion, rank), "MG"])
            estimates[exclusion].append(value)
            yield Computed(row, column, value, Data.name(rel))

    truth_array = np.array(truths)
    # Both readings of the row label produce a number and only one of them is what the
    # article prints, so the label decides which is compared and the claim records it.
    label = table.rows[table.find("absolute error")].label()
    by_median = "median" in _norm(label)
    summarise = ((lambda s: float(np.median(np.abs(s - truth_array)))) if by_median
                 else (lambda s: _mae(s, truth_array)))
    alternatives = []
    for column, exclusion in enumerate(exclusions, start=2):
        series = np.array(estimates[exclusion])
        yield Computed(table.find("absolute error"), column, summarise(series),
                       Data.name(rel))
        yield Computed(table.find("Spearman"), column, _spearman(series, truth_array),
                       Data.name(rel))
        other = (_mae(series, truth_array) if by_median
                 else float(np.median(np.abs(series - truth_array))))
        alternatives.append(other)

    yield Claim(
        row="absolute error",
        statement=f"the row is the {label}",
        holds=not by_median,
        finding=("the row is read as the mean, which is what the article prints; the "
                 f"median over the {len(truths)} ranks would be "
                 f"{' / '.join(f'{m:.2f}' for m in alternatives)}" if not by_median else
                 f"the printed values are the mean absolute error; the median over the "
                 f"{len(truths)} ranks is {' / '.join(f'{m:.2f}' for m in alternatives)}"),
        source=Data.name(rel))


# Article run -> the files that record it.
_SKETCHED_RUNS = ("mod_wd1", "mod_wd1_s43", "mod_wd1_s44", "s5_wd1", "mod_wd0", "s5_wd0")
_EXTENDED_RUNS = ("grokpos_s0", "lowdata15_s0", "lowdata15_s1", "lowdata15_s2",
                  "lowdata20_s0", "wd0_s0", "wd0_s1")

# How close the deepest analysis window must come to the printed budget. The windows slide
# to the end of the record, so a run that reached its budget leaves one within a stride of
# it; anything short of this means the run stopped early and the inventory is wrong.
BUDGET_TOLERANCE = 0.02


def _registry_configs() -> Dict[str, Any]:
    """Every run of appendix O, transformer and perceptron, under the name the table uses.

    The budget column has no source under ``data/``: the milestone files record what a run
    reached, not what it was given. The registry is that record, and it is the only place
    that says ``a_sum_sq`` ran 46,000 steps against the 100k the table prints.
    """
    from .training import runs as transformer_registry
    from .training import runs_perceptron as perceptron_registry

    configs: Dict[str, Any] = dict(transformer_registry.TRANSFORMER_RUNS)
    for key in perceptron_registry.INVENTORY:
        configs[key] = perceptron_registry.RUNS[key]
    return configs


def check_runs(table: Table, data: Data) -> Iterable[Any]:
    from .training import runs_perceptron as perceptron_registry

    summary = data.frame("grok.rank.dip/rank_summary.csv").set_index("run")
    milestones = {record["run"]: record
                  for record in data.json("grok.rank.dip/rank_milestones.json")}
    windows = data.frame("grok.rank.dip/rank_windows.csv")
    outcomes = data.frame("grok.extended.outcomes/exp8_outcomes.csv").set_index("run")
    log_windows = data.frame("grok.diagnostics.logs/real_logs_windows.csv")
    summary_file = Data.name("grok.rank.dip/rank_summary.csv")
    milestone_file = Data.name("grok.rank.dip/rank_milestones.json")
    window_file = Data.name("grok.rank.dip/rank_windows.csv")
    outcome_file = Data.name("grok.extended.outcomes/exp8_outcomes.csv")
    log_file = Data.name("grok.diagnostics.logs/real_logs_windows.csv")

    configs = _registry_configs()
    registry_file = data.note_code("actdim.training.runs + runs_perceptron")
    paper_file = data.note_code(
        "actdim.training.runs_perceptron.PAPER_MILESTONES (this table, transcribed)")

    for row in table.body():
        run = table.printed(row, 0)
        config = configs.get(run)
        if config is not None:
            # Budget, weight decay and training fraction are configuration, and the
            # registry is where the configuration lives. Errata item 5 is this cell.
            yield Computed(row, 5, float(config.max_steps), registry_file,
                           "the budget the registry gives this run")
            yield Computed(row, 3, float(config.weight_decay), registry_file)
            yield Computed(row, 4, float(config.fraction), registry_file)

        if run in _SKETCHED_RUNS:
            record = summary.loc[run]
            yield Computed(row, 6, float(record.t_mem), summary_file)
            yield Computed(row, 7, _nan_to_none(record.t_gen), summary_file)
            yield Computed(row, 8, float(record.final_val_acc), summary_file)
            # Two committed files carry these six rows. Both are compared, rather than one
            # trusted, so that a disagreement between them is reported here instead of
            # depending on which one a reader happened to open.
            stone = milestones.get(run)
            if stone is not None:
                yield Computed(row, 6, _nan_to_none(stone["t_mem"]), milestone_file)
                yield Computed(row, 7, _nan_to_none(stone["t_gen"]), milestone_file)
                yield Computed(row, 8, _nan_to_none(stone["final_val_acc"]), milestone_file)
            reach = windows[windows.run == run].right_step
            if not reach.empty:
                yield Computed(row, 5, _budget(table.printed(row, 5), reach.max()),
                               window_file, "the deepest analysis window in the record")
        elif run in _EXTENDED_RUNS:
            record = outcomes.loc[run]
            yield Computed(row, 6, float(record.t_mem), outcome_file)
            yield Computed(row, 7, _nan_to_none(record.t_gen), outcome_file)
            reach = log_windows[log_windows.run == run].right_step
            if not reach.empty:
                yield Computed(row, 5, _budget(table.printed(row, 5), reach.max()),
                               log_file, "the deepest analysis window in the record")
        elif run in perceptron_registry.PAPER_MILESTONES:
            # No committed file records a perceptron run's milestones. What the registry
            # holds is this table, transcribed, so the comparison catches the two drifting
            # apart and is not evidence that either is right.
            stone = perceptron_registry.PAPER_MILESTONES[run]
            yield Computed(row, 6, _nan_to_none(stone["memorise"]), paper_file)
            yield Computed(row, 7, _nan_to_none(stone["generalise"]), paper_file)
            yield Computed(row, 8, _nan_to_none(stone["final_val_acc"]), paper_file)

    # Errata item 11. The sentence under the table names the runs the sketch was attached
    # to, and it once named a different four from the campaign that ran. The names it gives
    # are read out of the article rather than assumed, so that changing either side is
    # reported instead of one of them being checked against a description of itself.
    sketched = tuple(perceptron_registry.SKETCHED)
    named = _runs_named_below(table)
    yield Claim(
        row="which four carry the sketch",
        statement=f"the sentence below the table names {', '.join(named) or 'no runs'}",
        holds=set(named) == set(sketched),
        finding=f"the campaign that ran sketched {', '.join(sketched)}",
        source=data.note_code("actdim.training.runs_perceptron.SKETCHED"))


def _runs_named_below(table: Table, lines: int = 12) -> Tuple[str, ...]:
    """The ``\\texttt`` run names in the paragraph that follows a table.

    Reads the article rather than the table, because the sentence under ``tab:runs`` is
    the thing being checked and it is prose.
    """
    source = article_path().read_text(encoding="utf-8").split("\n")
    start = next((i for i in range(table.line, len(source))
                  if "\\end{table}" in source[i]), None)
    if start is None:
        return ()
    block = "\n".join(source[start + 1:start + 1 + lines])
    block = block.split("\n\n")[0] if "\n\n" in block else block
    found = re.findall(r"\\texttt\{([^}]*)\}", block)
    seen: List[str] = []
    for name in (n.replace("\\_", "_") for n in found):
        if name not in seen:
            seen.append(name)
    return tuple(seen)


def _budget(printed: Optional[str], reach: Any) -> Optional[float]:
    """The printed budget, confirmed or contradicted by how far the record runs.

    Returned as the printed value when the record reaches it, and as the reach itself when
    it does not, so that a truncated run shows up as a mismatch naming the step it stopped
    at rather than as a silent pass.
    """
    stated = as_number(printed)
    reached = _nan_to_none(reach)
    if stated is None or reached is None:
        return None
    return stated if reached >= stated * (1.0 - BUDGET_TOLERANCE) else reached


_EOS_RATES = (1e5, 3e5, 1e6, 1.5e6, 2e6, 2.5e6, 2.8e6, 3e6)


def check_eos(table: Table, data: Data) -> Iterable[Any]:
    runs = data.frame("train.perceptron.eos/eos_runs.csv")
    recurrence = data.frame("grok.eos/eos_recurrence.csv")
    run_file = Data.name("train.perceptron.eos/eos_runs.csv")
    recurrence_file = Data.name("grok.eos/eos_recurrence.csv")

    # A run is comparable only at the campaign's budget. The run key is the rate and the
    # seed, so a short pass writes the same key as the full one, and a record left behind
    # by such a pass reports a rate at the edge of stability as monotone -- nothing has
    # happened yet at step 200. Those rows are named rather than averaged in.
    budget = int(runs.max_steps.max())
    short = runs[runs.max_steps < budget]
    # Reported whether or not any run is short. A check that says nothing when it passes
    # cannot be told from a check that was never made, and this one was added because the
    # committed table had carried two 200-step rows among fourteen 30,000-step ones.
    yield Claim(
        row="the campaign budget",
        statement=f"every run is {budget:,} steps",
        holds=short.empty,
        finding=(f"all {len(runs)} runs are" if short.empty else
                 "; ".join(f"{r.key} ran {int(r.max_steps):,}"
                           for _, r in short.iterrows())
                 + ". Those runs are left out of the comparison below"),
        source=run_file)
    runs = runs[runs.max_steps >= budget]

    body = table.body()
    for row, rate in zip(body, _EOS_RATES):
        at_rate = runs[np.abs(runs.lr - rate) < 1.0].sort_values("seed")
        if at_rate.empty:
            continue
        ratios, rises, returns = [], [], []
        for _, record in at_rate.iterrows():
            if _nan_to_none(record.diverged_at) is not None:
                ratios.append(None)
                rises.append(None)
                returns.append(None)
                continue
            ratios.append(float(record.eta_lam_over_2_median_tail))
            seed = recurrence[(np.abs(recurrence.lr - rate) < 1.0)
                              & (recurrence.seed == record.seed)]
            rises.append(float(seed.rises.median()) if not seed.empty else None)
            returns.append(float(seed.nn_over_travel.median()) if not seed.empty else None)
        yield Computed(row, 1, _collapse(ratios), run_file)
        yield Computed(row, 2, _collapse(rises), recurrence_file)
        yield Computed(row, 3, _collapse(returns), recurrence_file)


def _collapse(values: List[Optional[float]]) -> Any:
    """A per-seed list, or ``None`` where every seed diverged and the article prints a dash."""
    return None if all(v is None for v in values) else values


#: The two arms above the rule of ``tab:clocks``, and the five observer scales below it,
#: in the order the table prints them. Declared rather than parsed out of the row labels:
#: the article typesets the scales as ``$x + 0.25x^{3}$`` and the experiment records them
#: as ``x + 0.25 x^3``, and a checker that matched on those strings would break on a
#: purely typographical edit.
_CLOCK_ARMS = ("four independent clocks", "one clock, four hands")
_CLOCK_WARPS = ("identity", "x + 0.25 x^3", "x + x^3", "x + x^5", "x + 0.1 x^7")


def check_clocks(table: Table, data: Data) -> Iterable[Computed]:
    """Both halves of ``tab:clocks``: the roughness-matched arms, then the observer scales.

    Every cell is a median over the eight seeds, which is what the caption says it is.
    """
    levels = data.frame("valid.geometry/geometry_levels.csv")
    warps = data.frame("valid.geometry/observer_warps.csv")
    levels_file = Data.name("valid.geometry/geometry_levels.csv")
    warps_file = Data.name("valid.geometry/observer_warps.csv")

    body = table.body()
    for row, arm in zip(body, _CLOCK_ARMS):
        got = levels[levels.arm == arm]
        if got.empty:
            continue
        yield Computed(row, 1, float(got.truth.iloc[0]), levels_file)
        yield Computed(row, 2, float(got.MG.median()), levels_file)
        yield Computed(row, 3, float(got.matched_roughness.median()), levels_file)
        yield Computed(row, 4, float(got.PRdelay.median()), levels_file)

    for row, observer in zip(body[len(_CLOCK_ARMS):], _CLOCK_WARPS):
        got = warps[warps.observer == observer]
        if got.empty:
            continue
        # A monotone map cannot change an intrinsic dimension, so the truth column is 4
        # by construction rather than by measurement; the file records it per row.
        yield Computed(row, 1, float(got.truth.iloc[0]), warps_file)
        yield Computed(row, 2, float(got.MG.median()), warps_file)
        yield Computed(row, 3, float(got.observed_roughness.median()), warps_file)
        yield Computed(row, 4, float(got.PRdelay.median()), warps_file)


_CEILING_BLOCKS = (
    ("E", "max_E", (10, 14, 20, 28, 40, 56), "takens"),
    ("N", "N", (1000, 2000, 4000, 8000, 16000, 32000, 64000), "eckmann_ruelle"),
)


# Where the two scans meet: the third column of the first block and the fourth of the
# second are one cell, E_max = 20 at N = 8000, printed twice.
CEILING_SHARED = (2, 3)


def check_ceiling(table: Table, data: Data) -> Iterable[Any]:
    rel = "valid.ceiling/ceiling_summary.csv"
    frame = data.frame(rel)
    frame = frame[frame.arm == "frozen"]
    tracking = table.find_all("tracking")
    level = table.find_all("level at")
    slope = table.find_all("slope")
    predicts = table.find_all("predicts")
    rows = (("tracking", tracking, "r_track_1"), ("level at r = 20", level, "MG_at_20"),
            ("slope", slope, "slope_top"))

    for block, (sweep, axis, values, prediction) in enumerate(_CEILING_BLOCKS):
        part = frame[frame.sweep == sweep].set_index(axis)
        for column, value in enumerate(values, start=1):
            if value not in part.index:
                continue
            record = part.loc[value]
            name = f"{axis} = {value}"
            yield Computed(tracking[block], column, float(record.r_track_1), Data.name(rel),
                           column_name=name)
            yield Computed(predicts[block], column, float(record[prediction]),
                           Data.name(rel), column_name=name)
            yield Computed(level[block], column, float(record.MG_at_20), Data.name(rel),
                           column_name=name)
            yield Computed(slope[block], column, float(record.slope_top), Data.name(rel),
                           column_name=name)

    # The two scans share a cell, so the table can be checked against itself without any
    # file at all. Where the two printings disagree, one of them is wrong whatever the
    # measurement says.
    shared = frame[(frame.sweep == "N") & (frame.N == 8000)]
    for name, positions, column in rows:
        first = table.printed(positions[0], CEILING_SHARED[0] + 1)
        second = table.printed(positions[1], CEILING_SHARED[1] + 1)
        measured = float(shared.iloc[0][column]) if not shared.empty else float("nan")
        yield Claim(
            row=f"{name}, the shared cell",
            statement=(f"the two scans meet at E_max = 20, N = 8000, where the {name} row "
                       f"prints {first} in the first block and {second} in the second"),
            holds=first == second,
            finding=("the two agree" if first == second else
                     f"one cell printed two ways; the file gives {measured:.4f}"),
            source=Data.name(rel))


#: Row label -> the column of ``ceiling_fits.csv`` holding that form's error. The log-log
#: row is found by the ``log`` in its label rather than by one of its fitted constants: an
#: anchor that is itself a fitted number stops matching the moment the fit is redone, and
#: the table then goes unchecked with only a parse error to say so.
_CEILING_FITS = (("embedding condition", "rmse_takens"),
                 ("finite-record bound", "rmse_er"),
                 ("pointwise minimum", "rmse_min"),
                 ("log_10E", "rmse_loglog"))


def check_ceilingfit(table: Table, data: Data) -> Iterable[Any]:
    rel = "valid.ceiling/ceiling_fits.csv"
    frame = data.frame(rel)
    record = frame[frame.iloc[:, 0] == "MG_plateau"].iloc[0]
    for label, column in _CEILING_FITS:
        yield Computed(table.find(label), 1, float(record[column]), Data.name(rel))

    # The log-log row states its own coefficients, so they are compared as well as its error.
    row = table.rows[table.find("log_10E")]
    # The sign is written apart from the digits, so it is captured with them.
    printed = [as_number(t.replace(" ", ""))
               for t in re.findall(r"[-+]?\s*\d+\.\d+", row.label())]
    fitted = [float(record["loglog_dE"]), float(record["loglog_dN"]),
              float(record["loglog_const"])]
    yield Claim(
        row="the fitted log-log form",
        statement=row.label(),
        holds=(len(printed) == len(fitted)
               and all(round_half_up(a, 2) == round_half_up(b, 2)
                       for a, b in zip(printed, fitted))),
        finding=("%.2f log_10 E_max + %.2f log_10 N %+.2f" % tuple(fitted)),
        source=Data.name(rel))


# ---------------------------------------------------------------- the registry

@dataclass
class Registered:
    label: str
    check: Optional[Check]
    reason: str = ""
    notes: Tuple[str, ...] = ()


REGISTRY: Tuple[Registered, ...] = (
    Registered("tab:classes", None,
               "a definition: the three regimes and what the estimator returns in each"),
    Registered("tab:obsdef", None, "a definition: the twelve observers and their formulae"),
    Registered("tab:frozen", check_frozen, notes=(
        "the twenty-direction grid was never promoted, so that column's grid size and its "
        "two selection errors have no source under data/",
        "the swept-parameter and withheld-seed rows are prose",
    )),
    Registered("tab:geometry", check_geometry, notes=(
        "rows 2 and 3 state the convention the later pipelines use; no file records it",
    )),
    Registered("tab:ladder", check_ladder, notes=(
        "truth, range and the protocol column are statements about the design",
        "the error and the rank correlation are recomputed from heldout_raw.csv, one row "
        "per (rank, seed, observer); observer_ranking.csv is read as well so that a "
        "disagreement between the two committed files is reported rather than inherited",
    )),
    Registered("tab:aggregation", check_aggregation),
    Registered("tab:obs", check_obs, notes=(
        "the probe-accuracy row spans three columns to say the observer is degenerate; "
        "there is no number to check",
    )),
    Registered("tab:k20", check_k20),
    Registered("tab:alts", check_alts, notes=(
        "every printed cell reproduces; what fails is the claim above it, which is the "
        "shape errata item 3 has",
    )),
    Registered("tab:obsdep", None,
               "no file under data/ scores the two mode-weightings at several delay lags"),
    Registered("tab:tau", check_tau),
    Registered("tab:controls", check_controls, notes=(
        "the seven printed rows come from valid.nuisance/controls_scored.csv. "
        "calib.e20/invariance_controls.csv is a different sweep, of two controls at twenty "
        "directions, and settles the caption's two omissions rather than any printed cell",
    )),
    Registered("tab:switch", check_switch),
    Registered("tab:aniso", check_aniso),
    Registered("tab:gt", check_gt),
    Registered("tab:grok-diagnostics", check_grok_diagnostics, notes=(
        "the perceptron rows have no outcome record under data/, so the generalises column "
        "is checked only for the transformer runs",
    )),
    Registered("tab:dip", check_dip),
    Registered("tab:sketch", None,
               "the per-rank sketched and uncompressed participation ratios were not "
               "promoted; check.sketch.cost/sketch_cost.json records time and storage only"),
    Registered("tab:prwindow", check_prwindow, notes=(
        "the 600-step row is, by the caption, the earlier measurement rather than part of "
        "this sweep, and pr_vs_window.csv holds no window that short",
    )),
    Registered("tab:matched", check_matched, notes=(
        "the quantile column ranks the statistic among every window centre after "
        "memorisation; no committed file records that ranking",
        "the floor is compared to the nearest step: the S_5 runs log every five steps, so "
        "their window centres fall on half-steps and the article prints +712 for 712.5",
    )),
    Registered("tab:ipr-trajectory", None,
               "the Fourier inverse participation ratio of the trajectory is not in data/"),
    Registered("tab:ipr", None,
               "the first two columns are not in data/, and the grokking-step column "
               "repeats tab:runs, whose perceptron rows have no source either"),
    Registered("tab:theiler", check_theiler, notes=(
        "the row's own label decides which summary is compared, and is reported as a "
        "claim: both readings of it produce a number and only one is what is printed",
    )),
    Registered("tab:runs", check_runs, notes=(
        "the budget, the weight decay and the training fraction come from the run "
        "registry, which is code and not a file under data/. No committed file records a "
        "budget: the milestone files record what a run reached, not what it was given",
        "no committed file records a perceptron run's milestones either. The registry's "
        "PAPER_MILESTONES is this table transcribed, so the memorisation, generalisation "
        "and final-accuracy columns of the thirteen perceptron rows are checked against a "
        "copy of themselves. That catches the two drifting apart and is not evidence that "
        "either is right; promoting the arithmetic training logs would make it one",
        "the extended block's final accuracy is the value at the end of the budget, which "
        "no committed file records; exp8_outcomes.csv holds the maximum instead",
        "p211_wd0 has no log under data/, so only its configuration is checked",
        "the sentence below the table also claims the sketched runs agree with the rows "
        "above to within one or two logged steps (errata item 12). Settling that needs the "
        "milestones of both sketched campaigns, and neither train.perceptron.sketched.fb "
        "nor .mb has a milestones.csv under data/, so it is left unchecked here",
    )),
    Registered("tab:exclusion", None,
               "the recipe is not recoverable from the caption. Collapsing "
               "valid.theiler.contrast/sweep_windows.csv over observers, seeds and windows "
               "gives 5.43 / 2.07 / 1.20 in the first column against a printed "
               "5.39 / 2.11 / 1.20, and collapsing in another order moves every cell "
               "again without landing on the printed values"),
    Registered("tab:eos", check_eos, notes=(
        "the outcome column is a judgement; the divergence it reports is checked through "
        "the dashes in the three numeric columns",
    )),
    Registered("tab:ceiling", check_ceiling, notes=(
        "the two scans share the cell E_max = 20 at N = 8000, so three of its rows can be "
        "checked against the table itself before any file is opened",
    )),
    Registered("tab:ceilingfit", check_ceilingfit),
    Registered("tab:clocks", check_clocks, notes=(
        "the truth column is the construction, not a measurement: four independent "
        "phases against one, and an invertible map that cannot change either",
    )),
)


# ---------------------------------------------------------------- comparison

def compare(printed: Optional[str], computed: Any, tolerance: float = 0.0) -> Tuple[str, str]:
    """Diff one cell at the precision the article prints it to.

    Returns a status and a note. A value out by no more than one unit in the last printed
    place is ``rounding`` rather than ``mismatch``: the measurement agrees and the digits do
    not, which is a different defect and a different fix.
    """
    if isinstance(computed, (list, tuple)):
        return _compare_list(printed, list(computed), tolerance)
    if computed is None:
        if printed is None:
            return OK, ""
        return MISMATCH, "the file has no value here"
    if isinstance(computed, str):
        if printed is None:
            return MISMATCH, "the article prints a dash"
        return (OK, "") if _norm(printed) == _norm(computed) else (MISMATCH, "")
    if printed is None:
        return MISMATCH, "the article prints a dash"

    bound = re.match(r"^\s*([<>])\s*(.+)$", printed)
    if bound is not None:
        # A cell printed as "<0.001" states an inequality, and the inequality is what has
        # to hold. Reading it as unreadable left the two smallest roughness values in
        # tab:grok-diagnostics unchecked, which are the cells the claim beside them rests on.
        limit = as_number(bound.group(2))
        if limit is None:
            return UNREADABLE, f"{printed!r} is not a bound this check can read"
        if bound.group(1) == "<":
            return (OK, "") if computed < limit else (MISMATCH, f"not below {limit:g}")
        return (OK, "") if computed > limit else (MISMATCH, f"not above {limit:g}")

    target = as_number(printed)
    if target is None:
        return UNREADABLE, f"{printed!r} is not a number this check can read"
    if not np.isfinite(computed):
        return MISMATCH, "the recomputed value is not finite"

    if tolerance and abs(computed - target) <= tolerance + 1e-9:
        return OK, ""
    places = decimals(printed)
    if round_half_up(computed, places) == round_half_up(target, places):
        return OK, ""
    unit = 10.0 ** (-places)
    if abs(computed - target) <= unit + 1e-9:
        return ROUNDING, f"out by less than one unit in the last printed place ({unit:g})"
    return MISMATCH, ""


def _compare_list(printed: Optional[str], computed: List[Any],
                  tolerance: float = 0.0) -> Tuple[str, str]:
    if printed is None:
        return MISMATCH, "the article prints a dash where the file has values"
    parts = [p.strip() for p in re.split(r"[/,]", printed)]
    parts = [None if p in _MISSING else p for p in parts]
    if len(parts) == 1 and len(computed) > 1:
        # One printed value for several seeds, which the article does where they agree.
        parts = parts * len(computed)
    if len(parts) != len(computed):
        return MISMATCH, (f"the article prints {len(parts)} value(s) and the file has "
                          f"{len(computed)}")
    worst, notes = OK, []
    for part, value in zip(parts, computed):
        status, note = compare(part, value, tolerance)
        if status != OK:
            notes.append(f"{part}:{status}" + (f" ({note})" if note else ""))
            if worst == OK or status == MISMATCH:
                worst = status
    return worst, "; ".join(notes)


# ---------------------------------------------------------------- the audit

def audit(article: Optional[Path] = None, root: Optional[Path] = None,
          only: Optional[Sequence[str]] = None) -> Report:
    """Recompute every registered table and diff it against the article.

    Writes nothing. The caller decides what a mismatch is worth.
    """
    article = article or article_path()
    data = Data(root)
    tables = read_tables(article)
    results: List[TableResult] = []

    for entry in REGISTRY:
        if only and entry.label not in only:
            continue
        if entry.check is None:
            results.append(TableResult(entry.label, "skipped", entry.reason,
                                       notes=list(entry.notes)))
            continue
        table = tables.get(entry.label)
        if table is None:
            results.append(TableResult(entry.label, "skipped",
                                       "no table with this label in the article"))
            continue
        result = TableResult(entry.label, "checked", notes=list(entry.notes))
        try:
            computed = list(entry.check(table, data))
        except (ParseError, FileNotFoundError, KeyError, IndexError) as error:
            results.append(TableResult(entry.label, "skipped",
                                       f"{type(error).__name__}: {error}",
                                       notes=list(entry.notes)))
            continue
        for item in computed:
            if isinstance(item, Claim):
                result.findings.append(Finding(
                    label=entry.label,
                    row=item.row,
                    column=CLAIM,
                    printed=item.statement,
                    computed=item.finding,
                    source=item.source,
                    status=OK if item.holds else MISMATCH,
                    kind=CLAIM,
                    provenance=_provenance_of(item.source, data.read),
                ))
                continue
            printed = table.printed(item.row, item.column)
            status, note = compare(printed, item.value, item.tolerance)
            result.findings.append(Finding(
                label=entry.label,
                row=table.rows[item.row].label() or f"row {item.row}",
                column=item.column_name or table.column_label(item.column),
                printed=printed,
                computed=item.value if not isinstance(item.value, (list, tuple))
                else ", ".join("---" if v is None else f"{v:g}" for v in item.value),
                source=item.source,
                status=status,
                note="; ".join(part for part in (item.note, note) if part),
                provenance=_provenance_of(item.source, data.read),
            ))
        results.append(result)

    return Report(results=results, article=str(article), data=str(data.root),
                  inputs=dict(data.read))


def format_report(report: Report, verbose: bool = False) -> str:
    """The report as text: what was checked, what was not, and every disagreement."""
    lines: List[str] = []
    lines.append(f"article: {report.article}")
    lines.append(f"data:    {report.data}")
    lines.append("")

    checked = [r for r in report.results if r.state == "checked"]
    skipped = [r for r in report.results if r.state == "skipped"]
    cells = sum(r.checked for r in checked)
    bad = sum(len(r.mismatches) for r in checked)
    lines.append(f"{len(checked)} table(s) checked, {cells} cell(s) and claim(s) "
                 f"recomputed, {bad} disagreeing; {len(skipped)} table(s) not checked")

    archived = report.archived_inputs
    if archived:
        lines.append("")
        lines.append(f"{len(archived)} of {len(report.inputs)} input(s) are archived. A "
                     f"table checked against one has been checked against the numbers the "
                     f"article was written from, not against a regeneration:")
        for name in archived:
            lines.append(f"  archived  {name}")
        for name, state in sorted(report.inputs.items()):
            if state != ARCHIVED:
                lines.append(f"  {state:<9} {name}")
    lines.append("")

    for result in checked:
        mark = "OK " if not result.mismatches else "BAD"
        lines.append(f"[{mark}] {result.label:22s} {result.checked:4d} cell(s), "
                     f"{len(result.mismatches)} disagreeing")
        for finding in result.mismatches:
            lines.append("        " + finding.describe())
        if verbose:
            for finding in result.findings:
                if not finding.bad:
                    lines.append("    ok  " + finding.describe())
        for note in result.notes:
            lines.append(f"        note: {note}")

    if skipped:
        lines.append("")
        lines.append("not checked:")
        for result in skipped:
            lines.append(f"  {result.label:22s} {result.reason}")
            for note in result.notes:
                lines.append(f"        note: {note}")

    lines.append("")
    if report.ok:
        lines.append("every recomputed cell agrees with the article at the precision printed.")
    else:
        lines.append(f"{len(report.mismatches)} cell(s) disagree.")
    return "\n".join(lines)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--article", type=Path, default=None,
                        help="path to report.tex (default: ../icomp_v2/report.tex)")
    parser.add_argument("--data", type=Path, default=None,
                        help="path to the data tree (default: data/)")
    parser.add_argument("--table", action="append", default=None,
                        help="check only this label; repeatable")
    parser.add_argument("--verbose", action="store_true", help="list agreeing cells too")
    args = parser.parse_args(argv)

    report = audit(article=args.article, root=args.data, only=args.table)
    print(format_report(report, verbose=args.verbose))
    return 0 if report.ok else 1


if __name__ == "__main__":
    sys.exit(main())
